/***************************************************************************|
|  Jamm - Just another multimedia ...                                       |
|         ... set of applications and libraries based on the UPnP-AV specs  |
|                                                                           |
|  Copyright (C) 2009                                                       |
|  Jörg Bakker (joerg'at'hakker'dot'de)                                     |
|                                                                           |
|  This file is part of Jamm.                                               |
|                                                                           |
|  Jamm is free software: you can redistribute it and/or modify             |
|  it under the terms of the GNU General Public License as published by     |
|  the Free Software Foundation version 3 of the License.                   |
|                                                                           |
|  Jamm is distributed in the hope that it will be useful,                  |
|  but WITHOUT ANY WARRANTY; without even the implied warranty of           |
|  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            |
|  GNU General Public License for more details.                             |
|                                                                           |
|  You should have received a copy of the GNU General Public License        |
|  along with this program.  If not, see <http://www.gnu.org/licenses/>.    |
***************************************************************************/

/***************************************************************************|
|                               WARNING                                     |
|        This file is generated by the jamm stub generator jammgen.         |
|       Don't edit, it will be overriden at the next run of jammgen.        |
***************************************************************************/

#include "MediaRendererCtrl.h"

void
AVTransportController::SetAVTransportURI(const Jamm::ui4& InstanceID, const std::string& CurrentURI, const std::string& CurrentURIMetaData)
{
    Jamm::Action* pAction = m_pService->getAction("SetAVTransportURI")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    pAction->setArgument<std::string>("CurrentURI", CurrentURI);
    pAction->setArgument<std::string>("CurrentURIMetaData", CurrentURIMetaData);
    m_pService->sendAction(pAction);
}

void
AVTransportController::GetMediaInfo(/*const Jamm::ui4& InstanceID, Jamm::ui4& NrTracks, std::string& MediaDuration, std::string& CurrentURI, std::string& CurrentURIMetaData, std::string& NextURI, std::string& NextURIMetaData, std::string& PlayMedium, std::string& RecordMedium, std::string& WriteStatus*/)
{
    Jamm::Action* pAction = m_pService->getAction("GetMediaInfo")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    m_pService->sendAction(pAction);
    NrTracks = pAction->getArgument<Jamm::ui4>("NrTracks");
    MediaDuration = pAction->getArgument<std::string>("MediaDuration");
    CurrentURI = pAction->getArgument<std::string>("CurrentURI");
    CurrentURIMetaData = pAction->getArgument<std::string>("CurrentURIMetaData");
    NextURI = pAction->getArgument<std::string>("NextURI");
    NextURIMetaData = pAction->getArgument<std::string>("NextURIMetaData");
    PlayMedium = pAction->getArgument<std::string>("PlayMedium");
    RecordMedium = pAction->getArgument<std::string>("RecordMedium");
    WriteStatus = pAction->getArgument<std::string>("WriteStatus");
}

void
AVTransportController::GetTransportInfo(const Jamm::ui4& InstanceID, std::string& CurrentTransportState, std::string& CurrentTransportStatus, std::string& CurrentSpeed)
{
    Jamm::Action* pAction = m_pService->getAction("GetTransportInfo")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    m_pService->sendAction(pAction);
    CurrentTransportState = pAction->getArgument<std::string>("CurrentTransportState");
    CurrentTransportStatus = pAction->getArgument<std::string>("CurrentTransportStatus");
    CurrentSpeed = pAction->getArgument<std::string>("CurrentSpeed");
}

void
AVTransportController::GetPositionInfo(const Jamm::ui4& InstanceID, Jamm::ui4& Track, std::string& TrackDuration, std::string& TrackMetaData, std::string& TrackURI, std::string& RelTime, std::string& AbsTime, Jamm::i4& RelCount, Jamm::i4& AbsCount)
{
    Jamm::Action* pAction = m_pService->getAction("GetPositionInfo")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    m_pService->sendAction(pAction);
    Track = pAction->getArgument<Jamm::ui4>("Track");
    TrackDuration = pAction->getArgument<std::string>("TrackDuration");
    TrackMetaData = pAction->getArgument<std::string>("TrackMetaData");
    TrackURI = pAction->getArgument<std::string>("TrackURI");
    RelTime = pAction->getArgument<std::string>("RelTime");
    AbsTime = pAction->getArgument<std::string>("AbsTime");
    RelCount = pAction->getArgument<Jamm::i4>("RelCount");
    AbsCount = pAction->getArgument<Jamm::i4>("AbsCount");
}

void
AVTransportController::GetDeviceCapabilities(const Jamm::ui4& InstanceID, std::string& PlayMedia, std::string& RecMedia, std::string& RecQualityModes)
{
    Jamm::Action* pAction = m_pService->getAction("GetDeviceCapabilities")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    m_pService->sendAction(pAction);
    PlayMedia = pAction->getArgument<std::string>("PlayMedia");
    RecMedia = pAction->getArgument<std::string>("RecMedia");
    RecQualityModes = pAction->getArgument<std::string>("RecQualityModes");
}

void
AVTransportController::GetTransportSettings(const Jamm::ui4& InstanceID, std::string& PlayMode, std::string& RecQualityMode)
{
    Jamm::Action* pAction = m_pService->getAction("GetTransportSettings")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    m_pService->sendAction(pAction);
    PlayMode = pAction->getArgument<std::string>("PlayMode");
    RecQualityMode = pAction->getArgument<std::string>("RecQualityMode");
}

void
AVTransportController::Stop(const Jamm::ui4& InstanceID)
{
    Jamm::Action* pAction = m_pService->getAction("Stop")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    m_pService->sendAction(pAction);
}

void
AVTransportController::Play(const Jamm::ui4& InstanceID, const std::string& Speed)
{
    Jamm::Action* pAction = m_pService->getAction("Play")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    pAction->setArgument<std::string>("Speed", Speed);
    m_pService->sendAction(pAction);
}

void
AVTransportController::Pause(const Jamm::ui4& InstanceID)
{
    Jamm::Action* pAction = m_pService->getAction("Pause")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    m_pService->sendAction(pAction);
}

void
AVTransportController::Seek(const Jamm::ui4& InstanceID, const std::string& Unit, const std::string& Target)
{
    Jamm::Action* pAction = m_pService->getAction("Seek")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    pAction->setArgument<std::string>("Unit", Unit);
    pAction->setArgument<std::string>("Target", Target);
    m_pService->sendAction(pAction);
}

void
AVTransportController::Next(const Jamm::ui4& InstanceID)
{
    Jamm::Action* pAction = m_pService->getAction("Next")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    m_pService->sendAction(pAction);
}

void
AVTransportController::Previous(const Jamm::ui4& InstanceID)
{
    Jamm::Action* pAction = m_pService->getAction("Previous")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    m_pService->sendAction(pAction);
}

std::string
AVTransportController::_getLastChange()
{
    return m_pService->getStateVar<std::string>("LastChange");
}


void 
AVTransportController::_reqSetAVTransportURI(const Jamm::ui4& InstanceID, const std::string& CurrentURI, const std::string& CurrentURIMetaData)
{
    Jamm::Action* pAction = m_pService->getAction("SetAVTransportURI")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    pAction->setArgument<std::string>("CurrentURI", CurrentURI);
    pAction->setArgument<std::string>("CurrentURIMetaData", CurrentURIMetaData);
    Jamm::ActionThread<AVTransportController> thread(this, &AVTransportController::_threadSetAVTransportURI, pAction);
    thread.start();
}

void 
AVTransportController::_reqGetMediaInfo(const Jamm::ui4& InstanceID, )
{
    Jamm::Action* pAction = m_pService->getAction("GetMediaInfo")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    Jamm::ActionThread<AVTransportController> thread(this, &AVTransportController::_threadGetMediaInfo, pAction);
    thread.start();
}

void 
AVTransportController::_reqGetTransportInfo(const Jamm::ui4& InstanceID, )
{
    Jamm::Action* pAction = m_pService->getAction("GetTransportInfo")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    Jamm::ActionThread<AVTransportController> thread(this, &AVTransportController::_threadGetTransportInfo, pAction);
    thread.start();
}

void 
AVTransportController::_reqGetPositionInfo(const Jamm::ui4& InstanceID, )
{
    Jamm::Action* pAction = m_pService->getAction("GetPositionInfo")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    Jamm::ActionThread<AVTransportController> thread(this, &AVTransportController::_threadGetPositionInfo, pAction);
    thread.start();
}

void 
AVTransportController::_reqGetDeviceCapabilities(const Jamm::ui4& InstanceID, )
{
    Jamm::Action* pAction = m_pService->getAction("GetDeviceCapabilities")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    Jamm::ActionThread<AVTransportController> thread(this, &AVTransportController::_threadGetDeviceCapabilities, pAction);
    thread.start();
}

void 
AVTransportController::_reqGetTransportSettings(const Jamm::ui4& InstanceID, )
{
    Jamm::Action* pAction = m_pService->getAction("GetTransportSettings")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    Jamm::ActionThread<AVTransportController> thread(this, &AVTransportController::_threadGetTransportSettings, pAction);
    thread.start();
}

void 
AVTransportController::_reqStop(const Jamm::ui4& InstanceID)
{
    Jamm::Action* pAction = m_pService->getAction("Stop")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    Jamm::ActionThread<AVTransportController> thread(this, &AVTransportController::_threadStop, pAction);
    thread.start();
}

void 
AVTransportController::_reqPlay(const Jamm::ui4& InstanceID, const std::string& Speed)
{
    Jamm::Action* pAction = m_pService->getAction("Play")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    pAction->setArgument<std::string>("Speed", Speed);
    Jamm::ActionThread<AVTransportController> thread(this, &AVTransportController::_threadPlay, pAction);
    thread.start();
}

void 
AVTransportController::_reqPause(const Jamm::ui4& InstanceID)
{
    Jamm::Action* pAction = m_pService->getAction("Pause")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    Jamm::ActionThread<AVTransportController> thread(this, &AVTransportController::_threadPause, pAction);
    thread.start();
}

void 
AVTransportController::_reqSeek(const Jamm::ui4& InstanceID, const std::string& Unit, const std::string& Target)
{
    Jamm::Action* pAction = m_pService->getAction("Seek")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    pAction->setArgument<std::string>("Unit", Unit);
    pAction->setArgument<std::string>("Target", Target);
    Jamm::ActionThread<AVTransportController> thread(this, &AVTransportController::_threadSeek, pAction);
    thread.start();
}

void 
AVTransportController::_reqNext(const Jamm::ui4& InstanceID)
{
    Jamm::Action* pAction = m_pService->getAction("Next")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    Jamm::ActionThread<AVTransportController> thread(this, &AVTransportController::_threadNext, pAction);
    thread.start();
}

void 
AVTransportController::_reqPrevious(const Jamm::ui4& InstanceID)
{
    Jamm::Action* pAction = m_pService->getAction("Previous")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    Jamm::ActionThread<AVTransportController> thread(this, &AVTransportController::_threadPrevious, pAction);
    thread.start();
}

void 
AVTransportController::_threadSetAVTransportURI(Jamm::Action* pAction)
{
    m_pService->sendAction(pAction);
    Jamm::ui4 InstanceID = pAction->getArgument<Jamm::ui4>("InstanceID");
    std::string CurrentURI = pAction->getArgument<std::string>("CurrentURI");
    std::string CurrentURIMetaData = pAction->getArgument<std::string>("CurrentURIMetaData");
    _ansSetAVTransportURI(InstanceID, CurrentURI, CurrentURIMetaData);
}

void 
AVTransportController::_threadGetMediaInfo(Jamm::Action* pAction)
{
    m_pService->sendAction(pAction);
    Jamm::ui4 InstanceID = pAction->getArgument<Jamm::ui4>("InstanceID");
    Jamm::ui4 NrTracks = pAction->getArgument<Jamm::ui4>("NrTracks");
    std::string MediaDuration = pAction->getArgument<std::string>("MediaDuration");
    std::string CurrentURI = pAction->getArgument<std::string>("CurrentURI");
    std::string CurrentURIMetaData = pAction->getArgument<std::string>("CurrentURIMetaData");
    std::string NextURI = pAction->getArgument<std::string>("NextURI");
    std::string NextURIMetaData = pAction->getArgument<std::string>("NextURIMetaData");
    std::string PlayMedium = pAction->getArgument<std::string>("PlayMedium");
    std::string RecordMedium = pAction->getArgument<std::string>("RecordMedium");
    std::string WriteStatus = pAction->getArgument<std::string>("WriteStatus");
    _ansGetMediaInfo(InstanceID, NrTracks, MediaDuration, CurrentURI, CurrentURIMetaData, NextURI, NextURIMetaData, PlayMedium, RecordMedium, WriteStatus);
}

void 
AVTransportController::_threadGetTransportInfo(Jamm::Action* pAction)
{
    m_pService->sendAction(pAction);
    Jamm::ui4 InstanceID = pAction->getArgument<Jamm::ui4>("InstanceID");
    std::string CurrentTransportState = pAction->getArgument<std::string>("CurrentTransportState");
    std::string CurrentTransportStatus = pAction->getArgument<std::string>("CurrentTransportStatus");
    std::string CurrentSpeed = pAction->getArgument<std::string>("CurrentSpeed");
    _ansGetTransportInfo(InstanceID, CurrentTransportState, CurrentTransportStatus, CurrentSpeed);
}

void 
AVTransportController::_threadGetPositionInfo(Jamm::Action* pAction)
{
    m_pService->sendAction(pAction);
    Jamm::ui4 InstanceID = pAction->getArgument<Jamm::ui4>("InstanceID");
    Jamm::ui4 Track = pAction->getArgument<Jamm::ui4>("Track");
    std::string TrackDuration = pAction->getArgument<std::string>("TrackDuration");
    std::string TrackMetaData = pAction->getArgument<std::string>("TrackMetaData");
    std::string TrackURI = pAction->getArgument<std::string>("TrackURI");
    std::string RelTime = pAction->getArgument<std::string>("RelTime");
    std::string AbsTime = pAction->getArgument<std::string>("AbsTime");
    Jamm::i4 RelCount = pAction->getArgument<Jamm::i4>("RelCount");
    Jamm::i4 AbsCount = pAction->getArgument<Jamm::i4>("AbsCount");
    _ansGetPositionInfo(InstanceID, Track, TrackDuration, TrackMetaData, TrackURI, RelTime, AbsTime, RelCount, AbsCount);
}

void 
AVTransportController::_threadGetDeviceCapabilities(Jamm::Action* pAction)
{
    m_pService->sendAction(pAction);
    Jamm::ui4 InstanceID = pAction->getArgument<Jamm::ui4>("InstanceID");
    std::string PlayMedia = pAction->getArgument<std::string>("PlayMedia");
    std::string RecMedia = pAction->getArgument<std::string>("RecMedia");
    std::string RecQualityModes = pAction->getArgument<std::string>("RecQualityModes");
    _ansGetDeviceCapabilities(InstanceID, PlayMedia, RecMedia, RecQualityModes);
}

void 
AVTransportController::_threadGetTransportSettings(Jamm::Action* pAction)
{
    m_pService->sendAction(pAction);
    Jamm::ui4 InstanceID = pAction->getArgument<Jamm::ui4>("InstanceID");
    std::string PlayMode = pAction->getArgument<std::string>("PlayMode");
    std::string RecQualityMode = pAction->getArgument<std::string>("RecQualityMode");
    _ansGetTransportSettings(InstanceID, PlayMode, RecQualityMode);
}

void 
AVTransportController::_threadStop(Jamm::Action* pAction)
{
    m_pService->sendAction(pAction);
    Jamm::ui4 InstanceID = pAction->getArgument<Jamm::ui4>("InstanceID");
    _ansStop(InstanceID);
}

void 
AVTransportController::_threadPlay(Jamm::Action* pAction)
{
    m_pService->sendAction(pAction);
    Jamm::ui4 InstanceID = pAction->getArgument<Jamm::ui4>("InstanceID");
    std::string Speed = pAction->getArgument<std::string>("Speed");
    _ansPlay(InstanceID, Speed);
}

void 
AVTransportController::_threadPause(Jamm::Action* pAction)
{
    m_pService->sendAction(pAction);
    Jamm::ui4 InstanceID = pAction->getArgument<Jamm::ui4>("InstanceID");
    _ansPause(InstanceID);
}

void 
AVTransportController::_threadSeek(Jamm::Action* pAction)
{
    m_pService->sendAction(pAction);
    Jamm::ui4 InstanceID = pAction->getArgument<Jamm::ui4>("InstanceID");
    std::string Unit = pAction->getArgument<std::string>("Unit");
    std::string Target = pAction->getArgument<std::string>("Target");
    _ansSeek(InstanceID, Unit, Target);
}

void 
AVTransportController::_threadNext(Jamm::Action* pAction)
{
    m_pService->sendAction(pAction);
    Jamm::ui4 InstanceID = pAction->getArgument<Jamm::ui4>("InstanceID");
    _ansNext(InstanceID);
}

void 
AVTransportController::_threadPrevious(Jamm::Action* pAction)
{
    m_pService->sendAction(pAction);
    Jamm::ui4 InstanceID = pAction->getArgument<Jamm::ui4>("InstanceID");
    _ansPrevious(InstanceID);
}



void
ConnectionManagerController::GetProtocolInfo(std::string& Source, std::string& Sink)
{
    Jamm::Action* pAction = m_pService->getAction("GetProtocolInfo")->clone();
    m_pService->sendAction(pAction);
    Source = pAction->getArgument<std::string>("Source");
    Sink = pAction->getArgument<std::string>("Sink");
}

void
ConnectionManagerController::GetCurrentConnectionIDs(std::string& ConnectionIDs)
{
    Jamm::Action* pAction = m_pService->getAction("GetCurrentConnectionIDs")->clone();
    m_pService->sendAction(pAction);
    ConnectionIDs = pAction->getArgument<std::string>("ConnectionIDs");
}

void
ConnectionManagerController::GetCurrentConnectionInfo(const Jamm::i4& ConnectionID, Jamm::i4& RcsID, Jamm::i4& AVTransportID, std::string& ProtocolInfo, std::string& PeerConnectionManager, Jamm::i4& PeerConnectionID, std::string& Direction, std::string& Status)
{
    Jamm::Action* pAction = m_pService->getAction("GetCurrentConnectionInfo")->clone();
    pAction->setArgument<Jamm::i4>("ConnectionID", ConnectionID);
    m_pService->sendAction(pAction);
    RcsID = pAction->getArgument<Jamm::i4>("RcsID");
    AVTransportID = pAction->getArgument<Jamm::i4>("AVTransportID");
    ProtocolInfo = pAction->getArgument<std::string>("ProtocolInfo");
    PeerConnectionManager = pAction->getArgument<std::string>("PeerConnectionManager");
    PeerConnectionID = pAction->getArgument<Jamm::i4>("PeerConnectionID");
    Direction = pAction->getArgument<std::string>("Direction");
    Status = pAction->getArgument<std::string>("Status");
}

std::string
ConnectionManagerController::_getSourceProtocolInfo()
{
    return m_pService->getStateVar<std::string>("SourceProtocolInfo");
}

std::string
ConnectionManagerController::_getSinkProtocolInfo()
{
    return m_pService->getStateVar<std::string>("SinkProtocolInfo");
}

std::string
ConnectionManagerController::_getCurrentConnectionIDs()
{
    return m_pService->getStateVar<std::string>("CurrentConnectionIDs");
}


void 
ConnectionManagerController::_reqGetProtocolInfo()
{
    Jamm::Action* pAction = m_pService->getAction("GetProtocolInfo")->clone();
    Jamm::ActionThread<ConnectionManagerController> thread(this, &ConnectionManagerController::_threadGetProtocolInfo, pAction);
    thread.start();
}

void 
ConnectionManagerController::_reqGetCurrentConnectionIDs()
{
    Jamm::Action* pAction = m_pService->getAction("GetCurrentConnectionIDs")->clone();
    Jamm::ActionThread<ConnectionManagerController> thread(this, &ConnectionManagerController::_threadGetCurrentConnectionIDs, pAction);
    thread.start();
}

void 
ConnectionManagerController::_reqGetCurrentConnectionInfo(const Jamm::i4& ConnectionID, )
{
    Jamm::Action* pAction = m_pService->getAction("GetCurrentConnectionInfo")->clone();
    pAction->setArgument<Jamm::i4>("ConnectionID", ConnectionID);
    Jamm::ActionThread<ConnectionManagerController> thread(this, &ConnectionManagerController::_threadGetCurrentConnectionInfo, pAction);
    thread.start();
}

void 
ConnectionManagerController::_threadGetProtocolInfo(Jamm::Action* pAction)
{
    m_pService->sendAction(pAction);
    std::string Source = pAction->getArgument<std::string>("Source");
    std::string Sink = pAction->getArgument<std::string>("Sink");
    _ansGetProtocolInfo(Source, Sink);
}

void 
ConnectionManagerController::_threadGetCurrentConnectionIDs(Jamm::Action* pAction)
{
    m_pService->sendAction(pAction);
    std::string ConnectionIDs = pAction->getArgument<std::string>("ConnectionIDs");
    _ansGetCurrentConnectionIDs(ConnectionIDs);
}

void 
ConnectionManagerController::_threadGetCurrentConnectionInfo(Jamm::Action* pAction)
{
    m_pService->sendAction(pAction);
    Jamm::i4 ConnectionID = pAction->getArgument<Jamm::i4>("ConnectionID");
    Jamm::i4 RcsID = pAction->getArgument<Jamm::i4>("RcsID");
    Jamm::i4 AVTransportID = pAction->getArgument<Jamm::i4>("AVTransportID");
    std::string ProtocolInfo = pAction->getArgument<std::string>("ProtocolInfo");
    std::string PeerConnectionManager = pAction->getArgument<std::string>("PeerConnectionManager");
    Jamm::i4 PeerConnectionID = pAction->getArgument<Jamm::i4>("PeerConnectionID");
    std::string Direction = pAction->getArgument<std::string>("Direction");
    std::string Status = pAction->getArgument<std::string>("Status");
    _ansGetCurrentConnectionInfo(ConnectionID, RcsID, AVTransportID, ProtocolInfo, PeerConnectionManager, PeerConnectionID, Direction, Status);
}



void
RenderingControlController::ListPresets(const Jamm::ui4& InstanceID, std::string& CurrentPresetNameList)
{
    Jamm::Action* pAction = m_pService->getAction("ListPresets")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    m_pService->sendAction(pAction);
    CurrentPresetNameList = pAction->getArgument<std::string>("CurrentPresetNameList");
}

void
RenderingControlController::SelectPreset(const Jamm::ui4& InstanceID, const std::string& PresetName)
{
    Jamm::Action* pAction = m_pService->getAction("SelectPreset")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    pAction->setArgument<std::string>("PresetName", PresetName);
    m_pService->sendAction(pAction);
}

void
RenderingControlController::GetBrightness(const Jamm::ui4& InstanceID, Jamm::ui2& CurrentBrightness)
{
    Jamm::Action* pAction = m_pService->getAction("GetBrightness")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    m_pService->sendAction(pAction);
    CurrentBrightness = pAction->getArgument<Jamm::ui2>("CurrentBrightness");
}

void
RenderingControlController::SetBrightness(const Jamm::ui4& InstanceID, const Jamm::ui2& DesiredBrightness)
{
    Jamm::Action* pAction = m_pService->getAction("SetBrightness")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    pAction->setArgument<Jamm::ui2>("DesiredBrightness", DesiredBrightness);
    m_pService->sendAction(pAction);
}

void
RenderingControlController::GetContrast(const Jamm::ui4& InstanceID, Jamm::ui2& CurrentContrast)
{
    Jamm::Action* pAction = m_pService->getAction("GetContrast")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    m_pService->sendAction(pAction);
    CurrentContrast = pAction->getArgument<Jamm::ui2>("CurrentContrast");
}

void
RenderingControlController::SetContrast(const Jamm::ui4& InstanceID, const Jamm::ui2& DesiredContrast)
{
    Jamm::Action* pAction = m_pService->getAction("SetContrast")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    pAction->setArgument<Jamm::ui2>("DesiredContrast", DesiredContrast);
    m_pService->sendAction(pAction);
}

void
RenderingControlController::GetSharpness(const Jamm::ui4& InstanceID, Jamm::ui2& CurrentSharpness)
{
    Jamm::Action* pAction = m_pService->getAction("GetSharpness")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    m_pService->sendAction(pAction);
    CurrentSharpness = pAction->getArgument<Jamm::ui2>("CurrentSharpness");
}

void
RenderingControlController::SetSharpness(const Jamm::ui4& InstanceID, const Jamm::ui2& DesiredSharpness)
{
    Jamm::Action* pAction = m_pService->getAction("SetSharpness")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    pAction->setArgument<Jamm::ui2>("DesiredSharpness", DesiredSharpness);
    m_pService->sendAction(pAction);
}

void
RenderingControlController::GetRedVideoGain(const Jamm::ui4& InstanceID, Jamm::ui2& CurrentRedVideoGain)
{
    Jamm::Action* pAction = m_pService->getAction("GetRedVideoGain")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    m_pService->sendAction(pAction);
    CurrentRedVideoGain = pAction->getArgument<Jamm::ui2>("CurrentRedVideoGain");
}

void
RenderingControlController::SetRedVideoGain(const Jamm::ui4& InstanceID, const Jamm::ui2& DesiredRedVideoGain)
{
    Jamm::Action* pAction = m_pService->getAction("SetRedVideoGain")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    pAction->setArgument<Jamm::ui2>("DesiredRedVideoGain", DesiredRedVideoGain);
    m_pService->sendAction(pAction);
}

void
RenderingControlController::GetGreenVideoGain(const Jamm::ui4& InstanceID, Jamm::ui2& CurrentGreenVideoGain)
{
    Jamm::Action* pAction = m_pService->getAction("GetGreenVideoGain")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    m_pService->sendAction(pAction);
    CurrentGreenVideoGain = pAction->getArgument<Jamm::ui2>("CurrentGreenVideoGain");
}

void
RenderingControlController::SetGreenVideoGain(const Jamm::ui4& InstanceID, const Jamm::ui2& DesiredGreenVideoGain)
{
    Jamm::Action* pAction = m_pService->getAction("SetGreenVideoGain")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    pAction->setArgument<Jamm::ui2>("DesiredGreenVideoGain", DesiredGreenVideoGain);
    m_pService->sendAction(pAction);
}

void
RenderingControlController::GetBlueVideoGain(const Jamm::ui4& InstanceID, Jamm::ui2& CurrentBlueVideoGain)
{
    Jamm::Action* pAction = m_pService->getAction("GetBlueVideoGain")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    m_pService->sendAction(pAction);
    CurrentBlueVideoGain = pAction->getArgument<Jamm::ui2>("CurrentBlueVideoGain");
}

void
RenderingControlController::SetBlueVideoGain(const Jamm::ui4& InstanceID, const Jamm::ui2& DesiredBlueVideoGain)
{
    Jamm::Action* pAction = m_pService->getAction("SetBlueVideoGain")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    pAction->setArgument<Jamm::ui2>("DesiredBlueVideoGain", DesiredBlueVideoGain);
    m_pService->sendAction(pAction);
}

void
RenderingControlController::GetRedVideoBlackLevel(const Jamm::ui4& InstanceID, Jamm::ui2& CurrentRedVideoBlackLevel)
{
    Jamm::Action* pAction = m_pService->getAction("GetRedVideoBlackLevel")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    m_pService->sendAction(pAction);
    CurrentRedVideoBlackLevel = pAction->getArgument<Jamm::ui2>("CurrentRedVideoBlackLevel");
}

void
RenderingControlController::SetRedVideoBlackLevel(const Jamm::ui4& InstanceID, const Jamm::ui2& DesiredRedVideoBlackLevel)
{
    Jamm::Action* pAction = m_pService->getAction("SetRedVideoBlackLevel")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    pAction->setArgument<Jamm::ui2>("DesiredRedVideoBlackLevel", DesiredRedVideoBlackLevel);
    m_pService->sendAction(pAction);
}

void
RenderingControlController::GetGreenVideoBlackLevel(const Jamm::ui4& InstanceID, Jamm::ui2& CurrentGreenVideoBlackLevel)
{
    Jamm::Action* pAction = m_pService->getAction("GetGreenVideoBlackLevel")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    m_pService->sendAction(pAction);
    CurrentGreenVideoBlackLevel = pAction->getArgument<Jamm::ui2>("CurrentGreenVideoBlackLevel");
}

void
RenderingControlController::SetGreenVideoBlackLevel(const Jamm::ui4& InstanceID, const Jamm::ui2& DesiredGreenVideoBlackLevel)
{
    Jamm::Action* pAction = m_pService->getAction("SetGreenVideoBlackLevel")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    pAction->setArgument<Jamm::ui2>("DesiredGreenVideoBlackLevel", DesiredGreenVideoBlackLevel);
    m_pService->sendAction(pAction);
}

void
RenderingControlController::GetBlueVideoBlackLevel(const Jamm::ui4& InstanceID, Jamm::ui2& CurrentBlueVideoBlackLevel)
{
    Jamm::Action* pAction = m_pService->getAction("GetBlueVideoBlackLevel")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    m_pService->sendAction(pAction);
    CurrentBlueVideoBlackLevel = pAction->getArgument<Jamm::ui2>("CurrentBlueVideoBlackLevel");
}

void
RenderingControlController::SetBlueVideoBlackLevel(const Jamm::ui4& InstanceID, const Jamm::ui2& DesiredBlueVideoBlackLevel)
{
    Jamm::Action* pAction = m_pService->getAction("SetBlueVideoBlackLevel")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    pAction->setArgument<Jamm::ui2>("DesiredBlueVideoBlackLevel", DesiredBlueVideoBlackLevel);
    m_pService->sendAction(pAction);
}

void
RenderingControlController::GetColorTemperature (const Jamm::ui4& InstanceID, Jamm::ui2& CurrentColorTemperature)
{
    Jamm::Action* pAction = m_pService->getAction("GetColorTemperature ")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    m_pService->sendAction(pAction);
    CurrentColorTemperature = pAction->getArgument<Jamm::ui2>("CurrentColorTemperature");
}

void
RenderingControlController::SetColorTemperature(const Jamm::ui4& InstanceID, const Jamm::ui2& DesiredColorTemperature)
{
    Jamm::Action* pAction = m_pService->getAction("SetColorTemperature")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    pAction->setArgument<Jamm::ui2>("DesiredColorTemperature", DesiredColorTemperature);
    m_pService->sendAction(pAction);
}

void
RenderingControlController::GetHorizontalKeystone(const Jamm::ui4& InstanceID, Jamm::i2& CurrentHorizontalKeystone)
{
    Jamm::Action* pAction = m_pService->getAction("GetHorizontalKeystone")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    m_pService->sendAction(pAction);
    CurrentHorizontalKeystone = pAction->getArgument<Jamm::i2>("CurrentHorizontalKeystone");
}

void
RenderingControlController::SetHorizontalKeystone(const Jamm::ui4& InstanceID, const Jamm::i2& DesiredHorizontalKeystone)
{
    Jamm::Action* pAction = m_pService->getAction("SetHorizontalKeystone")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    pAction->setArgument<Jamm::i2>("DesiredHorizontalKeystone", DesiredHorizontalKeystone);
    m_pService->sendAction(pAction);
}

void
RenderingControlController::GetVerticalKeystone(const Jamm::ui4& InstanceID, Jamm::i2& CurrentVerticalKeystone)
{
    Jamm::Action* pAction = m_pService->getAction("GetVerticalKeystone")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    m_pService->sendAction(pAction);
    CurrentVerticalKeystone = pAction->getArgument<Jamm::i2>("CurrentVerticalKeystone");
}

void
RenderingControlController::SetVerticalKeystone(const Jamm::ui4& InstanceID, const Jamm::i2& DesiredVerticalKeystone)
{
    Jamm::Action* pAction = m_pService->getAction("SetVerticalKeystone")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    pAction->setArgument<Jamm::i2>("DesiredVerticalKeystone", DesiredVerticalKeystone);
    m_pService->sendAction(pAction);
}

void
RenderingControlController::GetMute(const Jamm::ui4& InstanceID, const std::string& Channel, bool& CurrentMute)
{
    Jamm::Action* pAction = m_pService->getAction("GetMute")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    pAction->setArgument<std::string>("Channel", Channel);
    m_pService->sendAction(pAction);
    CurrentMute = pAction->getArgument<bool>("CurrentMute");
}

void
RenderingControlController::SetMute(const Jamm::ui4& InstanceID, const std::string& Channel, const bool& DesiredMute)
{
    Jamm::Action* pAction = m_pService->getAction("SetMute")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    pAction->setArgument<std::string>("Channel", Channel);
    pAction->setArgument<bool>("DesiredMute", DesiredMute);
    m_pService->sendAction(pAction);
}

void
RenderingControlController::GetVolume(const Jamm::ui4& InstanceID, const std::string& Channel, Jamm::ui2& CurrentVolume)
{
    Jamm::Action* pAction = m_pService->getAction("GetVolume")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    pAction->setArgument<std::string>("Channel", Channel);
    m_pService->sendAction(pAction);
    CurrentVolume = pAction->getArgument<Jamm::ui2>("CurrentVolume");
}

void
RenderingControlController::SetVolume(const Jamm::ui4& InstanceID, const std::string& Channel, const Jamm::ui2& DesiredVolume)
{
    Jamm::Action* pAction = m_pService->getAction("SetVolume")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    pAction->setArgument<std::string>("Channel", Channel);
    pAction->setArgument<Jamm::ui2>("DesiredVolume", DesiredVolume);
    m_pService->sendAction(pAction);
}

void
RenderingControlController::GetVolumeDB(const Jamm::ui4& InstanceID, const std::string& Channel, Jamm::i2& CurrentVolume)
{
    Jamm::Action* pAction = m_pService->getAction("GetVolumeDB")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    pAction->setArgument<std::string>("Channel", Channel);
    m_pService->sendAction(pAction);
    CurrentVolume = pAction->getArgument<Jamm::i2>("CurrentVolume");
}

void
RenderingControlController::SetVolumeDB(const Jamm::ui4& InstanceID, const std::string& Channel, const Jamm::i2& DesiredVolume)
{
    Jamm::Action* pAction = m_pService->getAction("SetVolumeDB")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    pAction->setArgument<std::string>("Channel", Channel);
    pAction->setArgument<Jamm::i2>("DesiredVolume", DesiredVolume);
    m_pService->sendAction(pAction);
}

void
RenderingControlController::GetVolumeDBRange(const Jamm::ui4& InstanceID, const std::string& Channel, Jamm::i2& MinValue, Jamm::i2& MaxValue)
{
    Jamm::Action* pAction = m_pService->getAction("GetVolumeDBRange")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    pAction->setArgument<std::string>("Channel", Channel);
    m_pService->sendAction(pAction);
    MinValue = pAction->getArgument<Jamm::i2>("MinValue");
    MaxValue = pAction->getArgument<Jamm::i2>("MaxValue");
}

void
RenderingControlController::GetLoudness(const Jamm::ui4& InstanceID, const std::string& Channel, bool& CurrentLoudness)
{
    Jamm::Action* pAction = m_pService->getAction("GetLoudness")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    pAction->setArgument<std::string>("Channel", Channel);
    m_pService->sendAction(pAction);
    CurrentLoudness = pAction->getArgument<bool>("CurrentLoudness");
}

void
RenderingControlController::SetLoudness(const Jamm::ui4& InstanceID, const std::string& Channel, const bool& DesiredLoudness)
{
    Jamm::Action* pAction = m_pService->getAction("SetLoudness")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    pAction->setArgument<std::string>("Channel", Channel);
    pAction->setArgument<bool>("DesiredLoudness", DesiredLoudness);
    m_pService->sendAction(pAction);
}

std::string
RenderingControlController::_getLastChange()
{
    return m_pService->getStateVar<std::string>("LastChange");
}


void 
RenderingControlController::_reqListPresets(const Jamm::ui4& InstanceID, )
{
    Jamm::Action* pAction = m_pService->getAction("ListPresets")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    Jamm::ActionThread<RenderingControlController> thread(this, &RenderingControlController::_threadListPresets, pAction);
    thread.start();
}

void 
RenderingControlController::_reqSelectPreset(const Jamm::ui4& InstanceID, const std::string& PresetName)
{
    Jamm::Action* pAction = m_pService->getAction("SelectPreset")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    pAction->setArgument<std::string>("PresetName", PresetName);
    Jamm::ActionThread<RenderingControlController> thread(this, &RenderingControlController::_threadSelectPreset, pAction);
    thread.start();
}

void 
RenderingControlController::_reqGetBrightness(const Jamm::ui4& InstanceID, )
{
    Jamm::Action* pAction = m_pService->getAction("GetBrightness")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    Jamm::ActionThread<RenderingControlController> thread(this, &RenderingControlController::_threadGetBrightness, pAction);
    thread.start();
}

void 
RenderingControlController::_reqSetBrightness(const Jamm::ui4& InstanceID, const Jamm::ui2& DesiredBrightness)
{
    Jamm::Action* pAction = m_pService->getAction("SetBrightness")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    pAction->setArgument<Jamm::ui2>("DesiredBrightness", DesiredBrightness);
    Jamm::ActionThread<RenderingControlController> thread(this, &RenderingControlController::_threadSetBrightness, pAction);
    thread.start();
}

void 
RenderingControlController::_reqGetContrast(const Jamm::ui4& InstanceID, )
{
    Jamm::Action* pAction = m_pService->getAction("GetContrast")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    Jamm::ActionThread<RenderingControlController> thread(this, &RenderingControlController::_threadGetContrast, pAction);
    thread.start();
}

void 
RenderingControlController::_reqSetContrast(const Jamm::ui4& InstanceID, const Jamm::ui2& DesiredContrast)
{
    Jamm::Action* pAction = m_pService->getAction("SetContrast")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    pAction->setArgument<Jamm::ui2>("DesiredContrast", DesiredContrast);
    Jamm::ActionThread<RenderingControlController> thread(this, &RenderingControlController::_threadSetContrast, pAction);
    thread.start();
}

void 
RenderingControlController::_reqGetSharpness(const Jamm::ui4& InstanceID, )
{
    Jamm::Action* pAction = m_pService->getAction("GetSharpness")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    Jamm::ActionThread<RenderingControlController> thread(this, &RenderingControlController::_threadGetSharpness, pAction);
    thread.start();
}

void 
RenderingControlController::_reqSetSharpness(const Jamm::ui4& InstanceID, const Jamm::ui2& DesiredSharpness)
{
    Jamm::Action* pAction = m_pService->getAction("SetSharpness")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    pAction->setArgument<Jamm::ui2>("DesiredSharpness", DesiredSharpness);
    Jamm::ActionThread<RenderingControlController> thread(this, &RenderingControlController::_threadSetSharpness, pAction);
    thread.start();
}

void 
RenderingControlController::_reqGetRedVideoGain(const Jamm::ui4& InstanceID, )
{
    Jamm::Action* pAction = m_pService->getAction("GetRedVideoGain")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    Jamm::ActionThread<RenderingControlController> thread(this, &RenderingControlController::_threadGetRedVideoGain, pAction);
    thread.start();
}

void 
RenderingControlController::_reqSetRedVideoGain(const Jamm::ui4& InstanceID, const Jamm::ui2& DesiredRedVideoGain)
{
    Jamm::Action* pAction = m_pService->getAction("SetRedVideoGain")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    pAction->setArgument<Jamm::ui2>("DesiredRedVideoGain", DesiredRedVideoGain);
    Jamm::ActionThread<RenderingControlController> thread(this, &RenderingControlController::_threadSetRedVideoGain, pAction);
    thread.start();
}

void 
RenderingControlController::_reqGetGreenVideoGain(const Jamm::ui4& InstanceID, )
{
    Jamm::Action* pAction = m_pService->getAction("GetGreenVideoGain")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    Jamm::ActionThread<RenderingControlController> thread(this, &RenderingControlController::_threadGetGreenVideoGain, pAction);
    thread.start();
}

void 
RenderingControlController::_reqSetGreenVideoGain(const Jamm::ui4& InstanceID, const Jamm::ui2& DesiredGreenVideoGain)
{
    Jamm::Action* pAction = m_pService->getAction("SetGreenVideoGain")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    pAction->setArgument<Jamm::ui2>("DesiredGreenVideoGain", DesiredGreenVideoGain);
    Jamm::ActionThread<RenderingControlController> thread(this, &RenderingControlController::_threadSetGreenVideoGain, pAction);
    thread.start();
}

void 
RenderingControlController::_reqGetBlueVideoGain(const Jamm::ui4& InstanceID, )
{
    Jamm::Action* pAction = m_pService->getAction("GetBlueVideoGain")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    Jamm::ActionThread<RenderingControlController> thread(this, &RenderingControlController::_threadGetBlueVideoGain, pAction);
    thread.start();
}

void 
RenderingControlController::_reqSetBlueVideoGain(const Jamm::ui4& InstanceID, const Jamm::ui2& DesiredBlueVideoGain)
{
    Jamm::Action* pAction = m_pService->getAction("SetBlueVideoGain")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    pAction->setArgument<Jamm::ui2>("DesiredBlueVideoGain", DesiredBlueVideoGain);
    Jamm::ActionThread<RenderingControlController> thread(this, &RenderingControlController::_threadSetBlueVideoGain, pAction);
    thread.start();
}

void 
RenderingControlController::_reqGetRedVideoBlackLevel(const Jamm::ui4& InstanceID, )
{
    Jamm::Action* pAction = m_pService->getAction("GetRedVideoBlackLevel")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    Jamm::ActionThread<RenderingControlController> thread(this, &RenderingControlController::_threadGetRedVideoBlackLevel, pAction);
    thread.start();
}

void 
RenderingControlController::_reqSetRedVideoBlackLevel(const Jamm::ui4& InstanceID, const Jamm::ui2& DesiredRedVideoBlackLevel)
{
    Jamm::Action* pAction = m_pService->getAction("SetRedVideoBlackLevel")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    pAction->setArgument<Jamm::ui2>("DesiredRedVideoBlackLevel", DesiredRedVideoBlackLevel);
    Jamm::ActionThread<RenderingControlController> thread(this, &RenderingControlController::_threadSetRedVideoBlackLevel, pAction);
    thread.start();
}

void 
RenderingControlController::_reqGetGreenVideoBlackLevel(const Jamm::ui4& InstanceID, )
{
    Jamm::Action* pAction = m_pService->getAction("GetGreenVideoBlackLevel")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    Jamm::ActionThread<RenderingControlController> thread(this, &RenderingControlController::_threadGetGreenVideoBlackLevel, pAction);
    thread.start();
}

void 
RenderingControlController::_reqSetGreenVideoBlackLevel(const Jamm::ui4& InstanceID, const Jamm::ui2& DesiredGreenVideoBlackLevel)
{
    Jamm::Action* pAction = m_pService->getAction("SetGreenVideoBlackLevel")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    pAction->setArgument<Jamm::ui2>("DesiredGreenVideoBlackLevel", DesiredGreenVideoBlackLevel);
    Jamm::ActionThread<RenderingControlController> thread(this, &RenderingControlController::_threadSetGreenVideoBlackLevel, pAction);
    thread.start();
}

void 
RenderingControlController::_reqGetBlueVideoBlackLevel(const Jamm::ui4& InstanceID, )
{
    Jamm::Action* pAction = m_pService->getAction("GetBlueVideoBlackLevel")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    Jamm::ActionThread<RenderingControlController> thread(this, &RenderingControlController::_threadGetBlueVideoBlackLevel, pAction);
    thread.start();
}

void 
RenderingControlController::_reqSetBlueVideoBlackLevel(const Jamm::ui4& InstanceID, const Jamm::ui2& DesiredBlueVideoBlackLevel)
{
    Jamm::Action* pAction = m_pService->getAction("SetBlueVideoBlackLevel")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    pAction->setArgument<Jamm::ui2>("DesiredBlueVideoBlackLevel", DesiredBlueVideoBlackLevel);
    Jamm::ActionThread<RenderingControlController> thread(this, &RenderingControlController::_threadSetBlueVideoBlackLevel, pAction);
    thread.start();
}

void 
RenderingControlController::_reqGetColorTemperature (const Jamm::ui4& InstanceID, )
{
    Jamm::Action* pAction = m_pService->getAction("GetColorTemperature ")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    Jamm::ActionThread<RenderingControlController> thread(this, &RenderingControlController::_threadGetColorTemperature , pAction);
    thread.start();
}

void 
RenderingControlController::_reqSetColorTemperature(const Jamm::ui4& InstanceID, const Jamm::ui2& DesiredColorTemperature)
{
    Jamm::Action* pAction = m_pService->getAction("SetColorTemperature")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    pAction->setArgument<Jamm::ui2>("DesiredColorTemperature", DesiredColorTemperature);
    Jamm::ActionThread<RenderingControlController> thread(this, &RenderingControlController::_threadSetColorTemperature, pAction);
    thread.start();
}

void 
RenderingControlController::_reqGetHorizontalKeystone(const Jamm::ui4& InstanceID, )
{
    Jamm::Action* pAction = m_pService->getAction("GetHorizontalKeystone")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    Jamm::ActionThread<RenderingControlController> thread(this, &RenderingControlController::_threadGetHorizontalKeystone, pAction);
    thread.start();
}

void 
RenderingControlController::_reqSetHorizontalKeystone(const Jamm::ui4& InstanceID, const Jamm::i2& DesiredHorizontalKeystone)
{
    Jamm::Action* pAction = m_pService->getAction("SetHorizontalKeystone")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    pAction->setArgument<Jamm::i2>("DesiredHorizontalKeystone", DesiredHorizontalKeystone);
    Jamm::ActionThread<RenderingControlController> thread(this, &RenderingControlController::_threadSetHorizontalKeystone, pAction);
    thread.start();
}

void 
RenderingControlController::_reqGetVerticalKeystone(const Jamm::ui4& InstanceID, )
{
    Jamm::Action* pAction = m_pService->getAction("GetVerticalKeystone")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    Jamm::ActionThread<RenderingControlController> thread(this, &RenderingControlController::_threadGetVerticalKeystone, pAction);
    thread.start();
}

void 
RenderingControlController::_reqSetVerticalKeystone(const Jamm::ui4& InstanceID, const Jamm::i2& DesiredVerticalKeystone)
{
    Jamm::Action* pAction = m_pService->getAction("SetVerticalKeystone")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    pAction->setArgument<Jamm::i2>("DesiredVerticalKeystone", DesiredVerticalKeystone);
    Jamm::ActionThread<RenderingControlController> thread(this, &RenderingControlController::_threadSetVerticalKeystone, pAction);
    thread.start();
}

void 
RenderingControlController::_reqGetMute(const Jamm::ui4& InstanceID, const std::string& Channel, )
{
    Jamm::Action* pAction = m_pService->getAction("GetMute")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    pAction->setArgument<std::string>("Channel", Channel);
    Jamm::ActionThread<RenderingControlController> thread(this, &RenderingControlController::_threadGetMute, pAction);
    thread.start();
}

void 
RenderingControlController::_reqSetMute(const Jamm::ui4& InstanceID, const std::string& Channel, const bool& DesiredMute)
{
    Jamm::Action* pAction = m_pService->getAction("SetMute")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    pAction->setArgument<std::string>("Channel", Channel);
    pAction->setArgument<bool>("DesiredMute", DesiredMute);
    Jamm::ActionThread<RenderingControlController> thread(this, &RenderingControlController::_threadSetMute, pAction);
    thread.start();
}

void 
RenderingControlController::_reqGetVolume(const Jamm::ui4& InstanceID, const std::string& Channel, )
{
    Jamm::Action* pAction = m_pService->getAction("GetVolume")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    pAction->setArgument<std::string>("Channel", Channel);
    Jamm::ActionThread<RenderingControlController> thread(this, &RenderingControlController::_threadGetVolume, pAction);
    thread.start();
}

void 
RenderingControlController::_reqSetVolume(const Jamm::ui4& InstanceID, const std::string& Channel, const Jamm::ui2& DesiredVolume)
{
    Jamm::Action* pAction = m_pService->getAction("SetVolume")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    pAction->setArgument<std::string>("Channel", Channel);
    pAction->setArgument<Jamm::ui2>("DesiredVolume", DesiredVolume);
    Jamm::ActionThread<RenderingControlController> thread(this, &RenderingControlController::_threadSetVolume, pAction);
    thread.start();
}

void 
RenderingControlController::_reqGetVolumeDB(const Jamm::ui4& InstanceID, const std::string& Channel, )
{
    Jamm::Action* pAction = m_pService->getAction("GetVolumeDB")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    pAction->setArgument<std::string>("Channel", Channel);
    Jamm::ActionThread<RenderingControlController> thread(this, &RenderingControlController::_threadGetVolumeDB, pAction);
    thread.start();
}

void 
RenderingControlController::_reqSetVolumeDB(const Jamm::ui4& InstanceID, const std::string& Channel, const Jamm::i2& DesiredVolume)
{
    Jamm::Action* pAction = m_pService->getAction("SetVolumeDB")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    pAction->setArgument<std::string>("Channel", Channel);
    pAction->setArgument<Jamm::i2>("DesiredVolume", DesiredVolume);
    Jamm::ActionThread<RenderingControlController> thread(this, &RenderingControlController::_threadSetVolumeDB, pAction);
    thread.start();
}

void 
RenderingControlController::_reqGetVolumeDBRange(const Jamm::ui4& InstanceID, const std::string& Channel, )
{
    Jamm::Action* pAction = m_pService->getAction("GetVolumeDBRange")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    pAction->setArgument<std::string>("Channel", Channel);
    Jamm::ActionThread<RenderingControlController> thread(this, &RenderingControlController::_threadGetVolumeDBRange, pAction);
    thread.start();
}

void 
RenderingControlController::_reqGetLoudness(const Jamm::ui4& InstanceID, const std::string& Channel, )
{
    Jamm::Action* pAction = m_pService->getAction("GetLoudness")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    pAction->setArgument<std::string>("Channel", Channel);
    Jamm::ActionThread<RenderingControlController> thread(this, &RenderingControlController::_threadGetLoudness, pAction);
    thread.start();
}

void 
RenderingControlController::_reqSetLoudness(const Jamm::ui4& InstanceID, const std::string& Channel, const bool& DesiredLoudness)
{
    Jamm::Action* pAction = m_pService->getAction("SetLoudness")->clone();
    pAction->setArgument<Jamm::ui4>("InstanceID", InstanceID);
    pAction->setArgument<std::string>("Channel", Channel);
    pAction->setArgument<bool>("DesiredLoudness", DesiredLoudness);
    Jamm::ActionThread<RenderingControlController> thread(this, &RenderingControlController::_threadSetLoudness, pAction);
    thread.start();
}

void 
RenderingControlController::_threadListPresets(Jamm::Action* pAction)
{
    m_pService->sendAction(pAction);
    Jamm::ui4 InstanceID = pAction->getArgument<Jamm::ui4>("InstanceID");
    std::string CurrentPresetNameList = pAction->getArgument<std::string>("CurrentPresetNameList");
    _ansListPresets(InstanceID, CurrentPresetNameList);
}

void 
RenderingControlController::_threadSelectPreset(Jamm::Action* pAction)
{
    m_pService->sendAction(pAction);
    Jamm::ui4 InstanceID = pAction->getArgument<Jamm::ui4>("InstanceID");
    std::string PresetName = pAction->getArgument<std::string>("PresetName");
    _ansSelectPreset(InstanceID, PresetName);
}

void 
RenderingControlController::_threadGetBrightness(Jamm::Action* pAction)
{
    m_pService->sendAction(pAction);
    Jamm::ui4 InstanceID = pAction->getArgument<Jamm::ui4>("InstanceID");
    Jamm::ui2 CurrentBrightness = pAction->getArgument<Jamm::ui2>("CurrentBrightness");
    _ansGetBrightness(InstanceID, CurrentBrightness);
}

void 
RenderingControlController::_threadSetBrightness(Jamm::Action* pAction)
{
    m_pService->sendAction(pAction);
    Jamm::ui4 InstanceID = pAction->getArgument<Jamm::ui4>("InstanceID");
    Jamm::ui2 DesiredBrightness = pAction->getArgument<Jamm::ui2>("DesiredBrightness");
    _ansSetBrightness(InstanceID, DesiredBrightness);
}

void 
RenderingControlController::_threadGetContrast(Jamm::Action* pAction)
{
    m_pService->sendAction(pAction);
    Jamm::ui4 InstanceID = pAction->getArgument<Jamm::ui4>("InstanceID");
    Jamm::ui2 CurrentContrast = pAction->getArgument<Jamm::ui2>("CurrentContrast");
    _ansGetContrast(InstanceID, CurrentContrast);
}

void 
RenderingControlController::_threadSetContrast(Jamm::Action* pAction)
{
    m_pService->sendAction(pAction);
    Jamm::ui4 InstanceID = pAction->getArgument<Jamm::ui4>("InstanceID");
    Jamm::ui2 DesiredContrast = pAction->getArgument<Jamm::ui2>("DesiredContrast");
    _ansSetContrast(InstanceID, DesiredContrast);
}

void 
RenderingControlController::_threadGetSharpness(Jamm::Action* pAction)
{
    m_pService->sendAction(pAction);
    Jamm::ui4 InstanceID = pAction->getArgument<Jamm::ui4>("InstanceID");
    Jamm::ui2 CurrentSharpness = pAction->getArgument<Jamm::ui2>("CurrentSharpness");
    _ansGetSharpness(InstanceID, CurrentSharpness);
}

void 
RenderingControlController::_threadSetSharpness(Jamm::Action* pAction)
{
    m_pService->sendAction(pAction);
    Jamm::ui4 InstanceID = pAction->getArgument<Jamm::ui4>("InstanceID");
    Jamm::ui2 DesiredSharpness = pAction->getArgument<Jamm::ui2>("DesiredSharpness");
    _ansSetSharpness(InstanceID, DesiredSharpness);
}

void 
RenderingControlController::_threadGetRedVideoGain(Jamm::Action* pAction)
{
    m_pService->sendAction(pAction);
    Jamm::ui4 InstanceID = pAction->getArgument<Jamm::ui4>("InstanceID");
    Jamm::ui2 CurrentRedVideoGain = pAction->getArgument<Jamm::ui2>("CurrentRedVideoGain");
    _ansGetRedVideoGain(InstanceID, CurrentRedVideoGain);
}

void 
RenderingControlController::_threadSetRedVideoGain(Jamm::Action* pAction)
{
    m_pService->sendAction(pAction);
    Jamm::ui4 InstanceID = pAction->getArgument<Jamm::ui4>("InstanceID");
    Jamm::ui2 DesiredRedVideoGain = pAction->getArgument<Jamm::ui2>("DesiredRedVideoGain");
    _ansSetRedVideoGain(InstanceID, DesiredRedVideoGain);
}

void 
RenderingControlController::_threadGetGreenVideoGain(Jamm::Action* pAction)
{
    m_pService->sendAction(pAction);
    Jamm::ui4 InstanceID = pAction->getArgument<Jamm::ui4>("InstanceID");
    Jamm::ui2 CurrentGreenVideoGain = pAction->getArgument<Jamm::ui2>("CurrentGreenVideoGain");
    _ansGetGreenVideoGain(InstanceID, CurrentGreenVideoGain);
}

void 
RenderingControlController::_threadSetGreenVideoGain(Jamm::Action* pAction)
{
    m_pService->sendAction(pAction);
    Jamm::ui4 InstanceID = pAction->getArgument<Jamm::ui4>("InstanceID");
    Jamm::ui2 DesiredGreenVideoGain = pAction->getArgument<Jamm::ui2>("DesiredGreenVideoGain");
    _ansSetGreenVideoGain(InstanceID, DesiredGreenVideoGain);
}

void 
RenderingControlController::_threadGetBlueVideoGain(Jamm::Action* pAction)
{
    m_pService->sendAction(pAction);
    Jamm::ui4 InstanceID = pAction->getArgument<Jamm::ui4>("InstanceID");
    Jamm::ui2 CurrentBlueVideoGain = pAction->getArgument<Jamm::ui2>("CurrentBlueVideoGain");
    _ansGetBlueVideoGain(InstanceID, CurrentBlueVideoGain);
}

void 
RenderingControlController::_threadSetBlueVideoGain(Jamm::Action* pAction)
{
    m_pService->sendAction(pAction);
    Jamm::ui4 InstanceID = pAction->getArgument<Jamm::ui4>("InstanceID");
    Jamm::ui2 DesiredBlueVideoGain = pAction->getArgument<Jamm::ui2>("DesiredBlueVideoGain");
    _ansSetBlueVideoGain(InstanceID, DesiredBlueVideoGain);
}

void 
RenderingControlController::_threadGetRedVideoBlackLevel(Jamm::Action* pAction)
{
    m_pService->sendAction(pAction);
    Jamm::ui4 InstanceID = pAction->getArgument<Jamm::ui4>("InstanceID");
    Jamm::ui2 CurrentRedVideoBlackLevel = pAction->getArgument<Jamm::ui2>("CurrentRedVideoBlackLevel");
    _ansGetRedVideoBlackLevel(InstanceID, CurrentRedVideoBlackLevel);
}

void 
RenderingControlController::_threadSetRedVideoBlackLevel(Jamm::Action* pAction)
{
    m_pService->sendAction(pAction);
    Jamm::ui4 InstanceID = pAction->getArgument<Jamm::ui4>("InstanceID");
    Jamm::ui2 DesiredRedVideoBlackLevel = pAction->getArgument<Jamm::ui2>("DesiredRedVideoBlackLevel");
    _ansSetRedVideoBlackLevel(InstanceID, DesiredRedVideoBlackLevel);
}

void 
RenderingControlController::_threadGetGreenVideoBlackLevel(Jamm::Action* pAction)
{
    m_pService->sendAction(pAction);
    Jamm::ui4 InstanceID = pAction->getArgument<Jamm::ui4>("InstanceID");
    Jamm::ui2 CurrentGreenVideoBlackLevel = pAction->getArgument<Jamm::ui2>("CurrentGreenVideoBlackLevel");
    _ansGetGreenVideoBlackLevel(InstanceID, CurrentGreenVideoBlackLevel);
}

void 
RenderingControlController::_threadSetGreenVideoBlackLevel(Jamm::Action* pAction)
{
    m_pService->sendAction(pAction);
    Jamm::ui4 InstanceID = pAction->getArgument<Jamm::ui4>("InstanceID");
    Jamm::ui2 DesiredGreenVideoBlackLevel = pAction->getArgument<Jamm::ui2>("DesiredGreenVideoBlackLevel");
    _ansSetGreenVideoBlackLevel(InstanceID, DesiredGreenVideoBlackLevel);
}

void 
RenderingControlController::_threadGetBlueVideoBlackLevel(Jamm::Action* pAction)
{
    m_pService->sendAction(pAction);
    Jamm::ui4 InstanceID = pAction->getArgument<Jamm::ui4>("InstanceID");
    Jamm::ui2 CurrentBlueVideoBlackLevel = pAction->getArgument<Jamm::ui2>("CurrentBlueVideoBlackLevel");
    _ansGetBlueVideoBlackLevel(InstanceID, CurrentBlueVideoBlackLevel);
}

void 
RenderingControlController::_threadSetBlueVideoBlackLevel(Jamm::Action* pAction)
{
    m_pService->sendAction(pAction);
    Jamm::ui4 InstanceID = pAction->getArgument<Jamm::ui4>("InstanceID");
    Jamm::ui2 DesiredBlueVideoBlackLevel = pAction->getArgument<Jamm::ui2>("DesiredBlueVideoBlackLevel");
    _ansSetBlueVideoBlackLevel(InstanceID, DesiredBlueVideoBlackLevel);
}

void 
RenderingControlController::_threadGetColorTemperature (Jamm::Action* pAction)
{
    m_pService->sendAction(pAction);
    Jamm::ui4 InstanceID = pAction->getArgument<Jamm::ui4>("InstanceID");
    Jamm::ui2 CurrentColorTemperature = pAction->getArgument<Jamm::ui2>("CurrentColorTemperature");
    _ansGetColorTemperature (InstanceID, CurrentColorTemperature);
}

void 
RenderingControlController::_threadSetColorTemperature(Jamm::Action* pAction)
{
    m_pService->sendAction(pAction);
    Jamm::ui4 InstanceID = pAction->getArgument<Jamm::ui4>("InstanceID");
    Jamm::ui2 DesiredColorTemperature = pAction->getArgument<Jamm::ui2>("DesiredColorTemperature");
    _ansSetColorTemperature(InstanceID, DesiredColorTemperature);
}

void 
RenderingControlController::_threadGetHorizontalKeystone(Jamm::Action* pAction)
{
    m_pService->sendAction(pAction);
    Jamm::ui4 InstanceID = pAction->getArgument<Jamm::ui4>("InstanceID");
    Jamm::i2 CurrentHorizontalKeystone = pAction->getArgument<Jamm::i2>("CurrentHorizontalKeystone");
    _ansGetHorizontalKeystone(InstanceID, CurrentHorizontalKeystone);
}

void 
RenderingControlController::_threadSetHorizontalKeystone(Jamm::Action* pAction)
{
    m_pService->sendAction(pAction);
    Jamm::ui4 InstanceID = pAction->getArgument<Jamm::ui4>("InstanceID");
    Jamm::i2 DesiredHorizontalKeystone = pAction->getArgument<Jamm::i2>("DesiredHorizontalKeystone");
    _ansSetHorizontalKeystone(InstanceID, DesiredHorizontalKeystone);
}

void 
RenderingControlController::_threadGetVerticalKeystone(Jamm::Action* pAction)
{
    m_pService->sendAction(pAction);
    Jamm::ui4 InstanceID = pAction->getArgument<Jamm::ui4>("InstanceID");
    Jamm::i2 CurrentVerticalKeystone = pAction->getArgument<Jamm::i2>("CurrentVerticalKeystone");
    _ansGetVerticalKeystone(InstanceID, CurrentVerticalKeystone);
}

void 
RenderingControlController::_threadSetVerticalKeystone(Jamm::Action* pAction)
{
    m_pService->sendAction(pAction);
    Jamm::ui4 InstanceID = pAction->getArgument<Jamm::ui4>("InstanceID");
    Jamm::i2 DesiredVerticalKeystone = pAction->getArgument<Jamm::i2>("DesiredVerticalKeystone");
    _ansSetVerticalKeystone(InstanceID, DesiredVerticalKeystone);
}

void 
RenderingControlController::_threadGetMute(Jamm::Action* pAction)
{
    m_pService->sendAction(pAction);
    Jamm::ui4 InstanceID = pAction->getArgument<Jamm::ui4>("InstanceID");
    std::string Channel = pAction->getArgument<std::string>("Channel");
    bool CurrentMute = pAction->getArgument<bool>("CurrentMute");
    _ansGetMute(InstanceID, Channel, CurrentMute);
}

void 
RenderingControlController::_threadSetMute(Jamm::Action* pAction)
{
    m_pService->sendAction(pAction);
    Jamm::ui4 InstanceID = pAction->getArgument<Jamm::ui4>("InstanceID");
    std::string Channel = pAction->getArgument<std::string>("Channel");
    bool DesiredMute = pAction->getArgument<bool>("DesiredMute");
    _ansSetMute(InstanceID, Channel, DesiredMute);
}

void 
RenderingControlController::_threadGetVolume(Jamm::Action* pAction)
{
    m_pService->sendAction(pAction);
    Jamm::ui4 InstanceID = pAction->getArgument<Jamm::ui4>("InstanceID");
    std::string Channel = pAction->getArgument<std::string>("Channel");
    Jamm::ui2 CurrentVolume = pAction->getArgument<Jamm::ui2>("CurrentVolume");
    _ansGetVolume(InstanceID, Channel, CurrentVolume);
}

void 
RenderingControlController::_threadSetVolume(Jamm::Action* pAction)
{
    m_pService->sendAction(pAction);
    Jamm::ui4 InstanceID = pAction->getArgument<Jamm::ui4>("InstanceID");
    std::string Channel = pAction->getArgument<std::string>("Channel");
    Jamm::ui2 DesiredVolume = pAction->getArgument<Jamm::ui2>("DesiredVolume");
    _ansSetVolume(InstanceID, Channel, DesiredVolume);
}

void 
RenderingControlController::_threadGetVolumeDB(Jamm::Action* pAction)
{
    m_pService->sendAction(pAction);
    Jamm::ui4 InstanceID = pAction->getArgument<Jamm::ui4>("InstanceID");
    std::string Channel = pAction->getArgument<std::string>("Channel");
    Jamm::i2 CurrentVolume = pAction->getArgument<Jamm::i2>("CurrentVolume");
    _ansGetVolumeDB(InstanceID, Channel, CurrentVolume);
}

void 
RenderingControlController::_threadSetVolumeDB(Jamm::Action* pAction)
{
    m_pService->sendAction(pAction);
    Jamm::ui4 InstanceID = pAction->getArgument<Jamm::ui4>("InstanceID");
    std::string Channel = pAction->getArgument<std::string>("Channel");
    Jamm::i2 DesiredVolume = pAction->getArgument<Jamm::i2>("DesiredVolume");
    _ansSetVolumeDB(InstanceID, Channel, DesiredVolume);
}

void 
RenderingControlController::_threadGetVolumeDBRange(Jamm::Action* pAction)
{
    m_pService->sendAction(pAction);
    Jamm::ui4 InstanceID = pAction->getArgument<Jamm::ui4>("InstanceID");
    std::string Channel = pAction->getArgument<std::string>("Channel");
    Jamm::i2 MinValue = pAction->getArgument<Jamm::i2>("MinValue");
    Jamm::i2 MaxValue = pAction->getArgument<Jamm::i2>("MaxValue");
    _ansGetVolumeDBRange(InstanceID, Channel, MinValue, MaxValue);
}

void 
RenderingControlController::_threadGetLoudness(Jamm::Action* pAction)
{
    m_pService->sendAction(pAction);
    Jamm::ui4 InstanceID = pAction->getArgument<Jamm::ui4>("InstanceID");
    std::string Channel = pAction->getArgument<std::string>("Channel");
    bool CurrentLoudness = pAction->getArgument<bool>("CurrentLoudness");
    _ansGetLoudness(InstanceID, Channel, CurrentLoudness);
}

void 
RenderingControlController::_threadSetLoudness(Jamm::Action* pAction)
{
    m_pService->sendAction(pAction);
    Jamm::ui4 InstanceID = pAction->getArgument<Jamm::ui4>("InstanceID");
    std::string Channel = pAction->getArgument<std::string>("Channel");
    bool DesiredLoudness = pAction->getArgument<bool>("DesiredLoudness");
    _ansSetLoudness(InstanceID, Channel, DesiredLoudness);
}



void
MediaRendererController::eventHandler(Jamm::StateVar* pStateVar)
{
    if (pStateVar->getName() == "LastChange") {
        std::string val;
        pStateVar->getValue(val);
        m_pAVTransportController->_changedLastChange(val);
    }
    else if (pStateVar->getName() == "SourceProtocolInfo") {
        std::string val;
        pStateVar->getValue(val);
        m_pConnectionManagerController->_changedSourceProtocolInfo(val);
    }
    else if (pStateVar->getName() == "SinkProtocolInfo") {
        std::string val;
        pStateVar->getValue(val);
        m_pConnectionManagerController->_changedSinkProtocolInfo(val);
    }
    else if (pStateVar->getName() == "CurrentConnectionIDs") {
        std::string val;
        pStateVar->getValue(val);
        m_pConnectionManagerController->_changedCurrentConnectionIDs(val);
    }
    else if (pStateVar->getName() == "LastChange") {
        std::string val;
        pStateVar->getValue(val);
        m_pRenderingControlController->_changedLastChange(val);
    }
}


MediaRendererController::MediaRendererController(Jamm::Device* pDevice, RenderingControlController* pRenderingControlController, ConnectionManagerController* pConnectionManagerController, AVTransportController* pAVTransportController) :
ControllerImplAdapter(pDevice),
m_pDevice(pDevice),
m_pRenderingControlController(pRenderingControlController), 
m_pConnectionManagerController(pConnectionManagerController), 
m_pAVTransportController(pAVTransportController)
{
    m_pRenderingControlController->m_pService = m_pDevice->getService("urn:schemas-upnp-org:service:RenderingControl:1");
    m_pConnectionManagerController->m_pService = m_pDevice->getService("urn:schemas-upnp-org:service:ConnectionManager:1");
    m_pAVTransportController->m_pService = m_pDevice->getService("urn:schemas-upnp-org:service:AVTransport:1");

    init();
}

