/***************************************************************************|
|                               WARNING                                     |
|        This file is generated by the jamm stub generator jammgen.         |
|                   RENAME THIS FILE BEFORE EDITING!                        |
|           It will be overriden at the next run of jammgen.                |
***************************************************************************/

#include "DimmableLightCtrlImpl.h"

void
DimmingControllerImpl::_ansSetLoadLevelTarget(const Jamm::ui1& newLoadlevelTarget)
{
// begin of your own code

// end of your own code
}


void
DimmingControllerImpl::_ansGetLoadLevelTarget(const Jamm::ui1& retLoadlevelTarget)
{
// begin of your own code

// end of your own code
}


void
DimmingControllerImpl::_ansGetLoadLevelStatus(const Jamm::ui1& retLoadlevelStatus)
{
// begin of your own code

// end of your own code
}


void
DimmingControllerImpl::_changedLoadLevelStatus(const Jamm::ui1& val)
{
// begin of your own code

// end of your own code
}


void
SwitchPowerControllerImpl::_ansSetTarget(const bool& NewTargetValue)
{
// begin of your own code

// end of your own code
}


void
SwitchPowerControllerImpl::_ansGetTarget(const bool& RetTargetValue)
{
// begin of your own code

// end of your own code
}


void
SwitchPowerControllerImpl::_ansGetStatus(const bool& ResultStatus)
{
// begin of your own code

// end of your own code
}


void
SwitchPowerControllerImpl::_changedStatus(const bool& val)
{
// begin of your own code

// end of your own code
}


