/***************************************************************************|
|                               WARNING                                     |
|        This file is generated by the omm stub generator ommgen.           |
|       Don't edit, it will be overriden at the next run of ommgen.         |
****************************************************************************/

#ifndef DIMMABLELIGHT_CTRL_IMPL_H
#define DIMMABLELIGHT_CTRL_IMPL_H

#include <Omm/Upnp.h>
#include "DimmableLightCtrl.h"

class DimmingControllerImpl : public DimmingController
{
private:
    virtual void _ansSetLoadLevelTarget(const Omm::ui1& newLoadlevelTarget);
    virtual void _ansGetLoadLevelTarget(const Omm::ui1& retLoadlevelTarget);
    virtual void _ansGetLoadLevelStatus(const Omm::ui1& retLoadlevelStatus);

    virtual void _changedLoadLevelStatus(const Omm::ui1& val);
};

class SwitchPowerControllerImpl : public SwitchPowerController
{
private:
    virtual void _ansSetTarget(const bool& NewTargetValue);
    virtual void _ansGetTarget(const bool& RetTargetValue);
    virtual void _ansGetStatus(const bool& ResultStatus);

    virtual void _changedStatus(const bool& val);
};

#endif

