/***************************************************************************|
|                               WARNING                                     |
|        This file is generated by the omm stub generator ommgen.           |
|       Don't edit, it will be overriden at the next run of ommgen.         |
****************************************************************************/

#ifndef DIMMABLELIGHT_IMPLEMENTATION_H
#define DIMMABLELIGHT_IMPLEMENTATION_H

#include "DimmableLight.h"

class DimmingImplementation : public Dimming
{
private:
    virtual void SetLoadLevelTarget(const Omm::ui1& newLoadlevelTarget);
    virtual void GetLoadLevelTarget(Omm::ui1& retLoadlevelTarget);
    virtual void GetLoadLevelStatus(Omm::ui1& retLoadlevelStatus);

    virtual void initStateVars();
};

class SwitchPowerImplementation : public SwitchPower
{
private:
    virtual void SetTarget(const bool& NewTargetValue);
    virtual void GetTarget(bool& RetTargetValue);
    virtual void GetStatus(bool& ResultStatus);

    virtual void initStateVars();
};

#endif

