######################################################################
# Automatically generated by qmake (1.07a) Mon Feb 6 21:58:58 2006
######################################################################

TEMPLATE = app
#CONFIG -= moc
INCLUDEPATH += .

# Input
SOURCES += svdrptest.cpp
