find_path(OMMPLUGIN_INCLUDE_DIR
Omm/Plugin/Webradio.h
PATHS ${CMAKE_INCLUDE_PATH}
)

find_library(OMMPLUGIN_SERVER_WEBRADIO
NAME ommserver-webradio
PATHS ${CMAKE_LIBRARY_PATH}
)

find_library(OMMPLUGIN_SERVER_FILE
NAME ommserver-file
PATHS ${CMAKE_LIBRARY_PATH}
)

set(OMMPLUGIN_LIBRARY
${OMMPLUGIN_SERVER_WEBRADIO}
${OMMPLUGIN_SERVER_FILE}
)

set(OMMPLUGIN_INCLUDE_DIRS
${OMMPLUGIN_INCLUDE_DIR}
)

set(OMMPLUGIN_LIBRARIES
${OMMPLUGIN_LIBRARY}
)

if(OMMPLUGIN_INCLUDE_DIR)
message(STATUS "Found OMM plugin headers in: " ${OMMPLUGIN_INCLUDE_DIR})
else(OMMPLUGIN_INCLUDE_DIR)
message(STATUS "OMM plugin headers not found")
endif(OMMPLUGIN_INCLUDE_DIR)

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(OMMPLUGIN DEFAULT_MSG OMMPLUGIN_LIBRARY OMMPLUGIN_INCLUDE_DIR)
mark_as_advanced(OMMPLUGIN_INCLUDE_DIR OMMPLUGIN_LIBRARY)
