/***************************************************************************|
|  OMM - Open Multimedia                                                    |
|                                                                           |
|  Copyright (C) 2009, 2010, 2011                                           |
|  Jörg Bakker (jb'at'open-multimedia.org)                                  |
|                                                                           |
|  This file is part of OMM.                                                |
|                                                                           |
|  OMM is free software: you can redistribute it and/or modify              |
|  it under the terms of the GNU General Public License as published by     |
|  the Free Software Foundation version 3 of the License.                   |
|                                                                           |
|  OMM is distributed in the hope that it will be useful,                   |
|  but WITHOUT ANY WARRANTY; without even the implied warranty of           |
|  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            |
|  GNU General Public License for more details.                             |
|                                                                           |
|  You should have received a copy of the GNU General Public License        |
|  along with this program.  If not, see <http://www.gnu.org/licenses/>.    |
 ***************************************************************************/

#include <Poco/String.h>

#include "ommgen.h"

std::string StubWriter::preamble = 
//"\
///***************************************************************************|\n\
//|  OMM - Open Multimedia                                                    |\n\
//|                                                                           |\n\
//|  Copyright (C) 2009, 2010, 2011                                           |\n\
//|  Jörg Bakker (jb'at'open-multimedia.org)                                  |\n\
//|                                                                           |\n\
//|  This file is part of OMM.                                                |\n\
//|                                                                           |\n\
//|  OMM is free software: you can redistribute it and/or modify              |\n\
//|  it under the terms of the GNU General Public License as published by     |\n\
//|  the Free Software Foundation version 3 of the License.                   |\n\
//|                                                                           |\n\
//|  OMM is distributed in the hope that it will be useful,                   |\n\
//|  but WITHOUT ANY WARRANTY; without even the implied warranty of           |\n\
//|  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the            |\n\
//|  GNU General Public License for more details.                             |\n\
//|                                                                           |\n\
//|  You should have received a copy of the GNU General Public License        |\n\
//|  along with this program.  If not, see <http://www.gnu.org/licenses/>.    |\n\
//***************************************************************************/\n
"\
\n\
/***************************************************************************|\n\
|                               WARNING                                     |\n\
|        This file is generated by the OMM stub generator ommgen.           |\n\
|       Don't edit, it will be overriden at the next run of ommgen.         |\n\
****************************************************************************/\n\
\n\
";

std::string StubWriter::samplePreamble = \
"\
/***************************************************************************|\n\
|                               WARNING                                     |\n\
|        This file is generated by the omm stub generator ommgen.           |\n\
|                   RENAME THIS FILE BEFORE EDITING!                        |\n\
|           It will be overriden at the next run of ommgen.                 |\n\
****************************************************************************/\n\
\n\
";

StubWriter::StubWriter(DeviceContainer* pDeviceContainer, const std::string& outputPath) :
_pDeviceContainer(pDeviceContainer),
_outputPath(outputPath)
{
    // TODO: honor subdevices, not only root device
    _deviceType = pDeviceContainer->getRootDevice()->getDeviceType();
    Omm::Urn deviceType(_deviceType);
    _deviceName = deviceType.getTypeName();
    _outputPath += "/";

    _typeMapper["boolean"] = "bool";
    _typeMapper["ui1"] = "Omm::ui1";
    _typeMapper["ui2"] = "Omm::ui2";
    _typeMapper["ui4"] = "Omm::ui4";
    _typeMapper["i1"] = "Omm::i1";
    _typeMapper["i2"] = "Omm::i2";
    _typeMapper["i4"] = "Omm::i4";
    _typeMapper["r4"] = "Omm::r4";
    _typeMapper["r8"] = "Omm::r8";
    _typeMapper["number"] = "Omm::number";
    _typeMapper["string"] = "std::string";
    _typeMapper["uri"] = "Omm::uri";
}


void
StubWriter::write()
{
    deviceContainer(*_pDeviceContainer);
    for (DeviceContainer::ServiceTypeIterator s = _pDeviceContainer->beginServiceType(); s != _pDeviceContainer->endServiceType(); ++s) {
        Service& rs = *((*s).second);
        serviceType(rs);
        std::cout << "service: " << rs.getServiceType() << std::endl;
        for (Service::ActionIterator a = rs.beginAction(); a != rs.endAction(); ++a) {
            Action& ra = **a;
            action(ra);
            std::cout << "action: " << ra.getName() << std::endl;
            for (Action::ArgumentIterator arg = ra.beginArgument(); arg != ra.endArgument(); ++arg) {
                int dist = distance(arg, ra.endArgument());
                Argument& rarg = **arg;
                argument(rarg, dist == 1);
            }
            actionEnd(ra);
        }
        actionBlockEnd();
        for (Service::StateVarIterator sv = rs.beginStateVar(); sv != rs.endStateVar(); ++sv) {
            StateVar& rsv = **sv;
            stateVar(rsv);
        }
        serviceTypeEnd(rs);
    }
    deviceContainerEnd(*_pDeviceContainer);
}


std::string
StubWriter::indent(int level)
{
    std::string res = "";
    while(level--) {
        res += "    ";
    }
    return res;
}


std::string
StubWriter::firstLetterToLower(const std::string& s)
{
    return Poco::toLower(s.substr(0, 1)) + s.substr(1);
}


DevDeviceH::DevDeviceH(DeviceContainer* pDeviceContainer, const std::string& outputPath) :
StubWriter(pDeviceContainer, outputPath),
_out((_outputPath + "Dev" + _deviceName + ".h").c_str())
{
}


void
DevDeviceH::deviceContainer(const DeviceContainer& deviceContainer)
{
    _out
        << preamble
        << "#ifndef " << Poco::toUpper(_deviceName) << "_H" << std::endl
        << "#define " << Poco::toUpper(_deviceName) << "_H" << std::endl
        << std::endl
        << "#include <Omm/Upnp.h>" << std::endl
        << std::endl
        << "using Omm::DevDevice;" << std::endl
        << "using Omm::Service;" << std::endl
        << "using Omm::Action;" << std::endl
        << "using Omm::StateVar;" << std::endl
        << "using Omm::StringDescriptionReader;" << std::endl
//        << "using Omm::ui1;" << std::endl
//        << "using Omm::ui2;" << std::endl
//        << "using Omm::ui4;" << std::endl
//        << "using Omm::i1;" << std::endl
//        << "using Omm::i2;" << std::endl
//        << "using Omm::i4;" << std::endl
//        << "using Omm::r4;" << std::endl
//        << "using Omm::r4;" << std::endl
//        << "using Omm::number;" << std::endl
//        << "using Omm::uri;" << std::endl
//        << "using Omm::date;" << std::endl
//        << "using Omm::dateTime;" << std::endl
//        << "using Omm::time;" << std::endl
        << std::endl
        << "class " << "Dev" + _deviceName << ";"
        << std::endl;
}


void
DevDeviceH::deviceContainerEnd(const DeviceContainer& deviceContainer)
{
    std::string ctorArgs = "";
//     std::string implPointers = "";
    int i = _serviceNames.size();
    while (i--) {
        ctorArgs += "Dev" + _serviceNames[i] + "* pDev" + _serviceNames[i] + "Impl" + (i ? ", " : "");
    }
    
    _out << std::endl
        << "class " << "Dev" + _deviceName << " : public DevDevice" << std::endl
        << "{" << std::endl
        << "public:" << std::endl
        << indent(1) << "Dev" + _deviceName << "("
        << ctorArgs
        << ");" << std::endl
        << std::endl
        << "private:" << std::endl
        << indent(1) << "virtual void actionHandler(Action* pAction);" << std::endl
        << indent(1) << "virtual void initStateVars(Service* pService);" << std::endl
        << std::endl
//        << indent(1) << "static std::string _deviceDescription;" << std::endl
        ;

    i = _serviceNames.size();
    while (i--) {
        _out << indent(1) << "Dev" + _serviceNames[i] << "* _pDev" << _serviceNames[i] << "Impl;" << std::endl;
    }

    _out
        << "};" << std::endl
        << std::endl
        << "#endif" << std::endl
        << std::endl;
}


void
DevDeviceH::serviceType(const Service& service)
{
    Omm::Urn serviceType(service.getServiceType());
    std::string serviceName = serviceType.getTypeName();
    _serviceNames.push_back(serviceName);
    
    _out << std::endl
        << "class " << "Dev" + serviceName << std::endl
        << "{" << std::endl
        << indent(1) << "friend class " << "Dev" + _deviceName << ";" << std::endl
        << std::endl
        << "protected:" << std::endl
        << indent(1) << "virtual ~Dev" + serviceName + "() {}" << std::endl
        << std::endl;
}


void
DevDeviceH::serviceTypeEnd(const Service& service)
{
    _out << std::endl
        << "private:" << std::endl
//        << indent(1) << "static std::string  _description;" << std::endl
        << indent(1) << "Service* _pService;" << std::endl
        << "};" << std::endl
        << std::endl;
}


void
DevDeviceH::action(const Action& action)
{
    _out
        << indent(1) << "virtual void " << action.getName() << "("
        ;
}


void
DevDeviceH::actionEnd(const Action& action)
{
    _out
        << ") = 0;"
        << std::endl;
}


void
DevDeviceH::actionBlockEnd()
{
    _out << std::endl
        << indent(1) << "virtual void initStateVars() = 0;" << std::endl
        << indent(1) << "void actionHandler(Action* pAction);" << std::endl
        << std::endl;
}


void
DevDeviceH::argument(const Argument& argument, bool lastArgument)
{
    _out
        << ((argument.getDirection() == "in") ? "const " : "")
        << _typeMapper[argument.getRelatedStateVarReference()->getType()]
        << "& " << argument.getName()
        << (lastArgument ? "" : ", ")
        ;
}


void
DevDeviceH::stateVar(const StateVar& stateVar)
{
    if (stateVar.getName().substr(0, std::string("A_ARG_TYPE_").size()) == "A_ARG_TYPE_") {
        return;
    }
    
    _out
        << indent(1) << "void _set" << stateVar.getName() << "(const "
        << _typeMapper[stateVar.getType()] << "& val);"
        << std::endl
        << indent(1) << _typeMapper[stateVar.getType()]
        << " _get" << stateVar.getName() << "();"
        << std::endl;
}


DevDeviceCpp::DevDeviceCpp(DeviceContainer* pDeviceContainer, const std::string& outputPath) :
StubWriter(pDeviceContainer, outputPath),
_out((_outputPath + "Dev" + _deviceName + ".cpp").c_str())
{
}


void
DevDeviceCpp::deviceContainer(const DeviceContainer& deviceContainer)
{
    _out
        << preamble
        << "#include \"" << "Dev" + _deviceName << "Disp.h\"" << std::endl
        << "#include \"" << _deviceName << "Desc.h\"" << std::endl
        << std::endl
        << std::endl
        << "void" << std::endl
        << "Dev" + _deviceName << "::actionHandler(Action* pAction)" << std::endl
        << "{" << std::endl
//        << indent(1) << "// the great action dispatcher" << std::endl;
        << indent(1) << "std::string serviceType = pAction->getService()->getServiceType();" << std::endl;
    
    _stateVarInitializer
        << "void" << std::endl
        << "Dev" + _deviceName << "::initStateVars(Service* pService)" << std::endl
        << "{" << std::endl
        << indent(1) <<  "std::string serviceType = pService->getServiceType();"
        << std::endl;
    
    _firstService = true;
}


void
DevDeviceCpp::deviceContainerEnd(const DeviceContainer& deviceContainer)
{
//    std::string deviceDescriptionPath = deviceContainer.getDescriptionUri();
    std::string deviceDescriptionPath = "/" + _deviceType + "/Description.xml";
    std::string ctorArgs = "";
    int i = _serviceNames.size();
    while (i--) {
        ctorArgs += "Dev" + _serviceNames[i] + "* p" + _serviceNames[i] + "Impl" + (i ? ", " : "");
    }
    
    _out
        << "}" << std::endl
        << std::endl
        << std::endl
        << _stateVarInitializer.str()
        << "}" << std::endl
        << std::endl
        << std::endl
        << "Dev" + _deviceName << "::" << _deviceName << "("
        << ctorArgs
        << ") :" << std::endl
        << "DevDevice()," << std::endl
        ;
    
    i = _serviceNames.size();
    while (i--) {
        _out 
            << "_p" << "Dev" + _serviceNames[i] << "Impl(p" << _serviceNames[i] << "Impl)"
            << (i ? ", " : "") << std::endl;
    }
    
    _out
        << "{" << std::endl
        << indent(1) << "_descriptions[\"" << deviceDescriptionPath << "\"]"
        << " = &" << "Dev" + _deviceName << "::_deviceDescription;" << std::endl;
    
    i = _serviceNames.size();
    while (i--) {
        _out
            << indent(1) << "_descriptions[\"" << _servicePaths[i] << "\"]"
//            << indent(1) << "_descriptions[\"/" << _serviceTypes[i] << "/Description.xml" << "\"]"
            << " = &" << "Dev" + _serviceNames[i] << "::_description;" << std::endl;
    }
    
//     _out << std::endl;
//     
//     i = _serviceNames.size();
//     while (i--) {
//         _out
//             << indent(1) << "p" << _serviceNames[i] << "Impl->_pMediaRenderer = this;"
//             << std::endl;
//     }
    
    _out << std::endl
        << indent(1) << "StringDescriptionReader descriptionReader(_descriptions);" << std::endl
//        << deviceDescriptionPath << "\");" << std::endl
        << indent(1) << "_pDeviceContainer = descriptionReader.deviceContainer(\""
//        <<  _deviceName << ".xml\");" << std::endl
        <<  deviceDescriptionPath << "\");" << std::endl
        << indent(1) << "_pDeviceContainer->setImplAdapter(this);" << std::endl
        << "}" << std::endl
        << std::endl
        << std::endl
        << _serviceActionDispatcher.str()
        << _getSet.str()
        << std::endl;
}


void
DevDeviceCpp::serviceType(const Service& service)
{
    _serviceTypes.push_back(service.getServiceType());
    std::string servicePath = "/" + service.getServiceType() + "/Description.xml";
//    std::string servicePath = service.getDescriptionPath();
//    service.setDescriptionPath(servicePath);
    _servicePaths.push_back(servicePath);
    Omm::Urn serviceType(service.getServiceType());
    std::string serviceName = serviceType.getTypeName();
    _serviceNames.push_back(serviceName);
    _currentService = serviceName;
    _firstAction = true;
    
    _out
        << indent(1) << (_firstService ? "" : "else ")
        << "if (serviceType == \""
        << service.getServiceType() << "\") {" << std::endl
//        << indent(2) << "_p" << serviceName << "Impl->_pService = pAction->getService();" << std::endl
//        << indent(2) << "std::string actionName = pAction->getName();" << std::endl
        << indent(2) << "_p" << serviceName << "Impl->actionHandler(pAction);"
        << std::endl;

    _serviceActionDispatcher
        << "void" << std::endl
        << "Dev" + _currentService << "::actionHandler(Action* pAction)" << std::endl
        << "{" << std::endl
        << indent(1) << "std::string actionName = pAction->getName();" << std::endl;
    
    _stateVarInitializer
        << indent(1) << (_firstService ? "" : "else ")
        << "if (serviceType == \"" << service.getServiceType() << "\") {" << std::endl
        << indent(2) << "_p" << serviceName << "Impl->_pService = pService;" << std::endl
        << indent(2) << "_p" << serviceName << "Impl->initStateVars();" << std::endl
        << indent(1) << "}" << std::endl;
    
    _firstService = false;
}


void
DevDeviceCpp::serviceTypeEnd(const Service& service)
{
    _out
        << indent(1) << "}"
        << std::endl;
    
    _serviceActionDispatcher
        << "}"
        << std::endl
        << std::endl
        << std::endl;
}


void
DevDeviceCpp::action(const Action& action)
{
    _serviceActionDispatcher
        << indent(1) << (_firstAction ? "" : "else ")
        << "if (actionName == \"" << action.getName() << "\") {" << std::endl
        ;
    _currentOutArgs = "";
    _currentOutArgSetter.str("");
    _firstAction = false;
}


void
DevDeviceCpp::actionEnd(const Action& action)
{
    _serviceActionDispatcher
        // do the implementation callback here
//        << indent(2) << "_p" << _currentService << "Impl->" << action.getName()
        << indent(2) << action.getName()
        << "(" << _currentOutArgs << ");" << std::endl
        << _currentOutArgSetter.str()
        << indent(1) << "}"
        << std::endl;
}


void
DevDeviceCpp::argument(const Argument& argument, bool lastArgument)
{
    std::string argType = _typeMapper[argument.getRelatedStateVarReference()->getType()];
    _serviceActionDispatcher
        << indent(2) << argType
        << " " /*<< argument.getDirection()*/ << argument.getName();
    if (argument.getDirection() == "in") {
        _serviceActionDispatcher
            << " = pAction->getArgument<" << argType << ">(\"" << argument.getName() << "\")";
    }
    _serviceActionDispatcher
        << ";" << std::endl;
    _currentOutArgs += /*(argument.getDirection() == "in" ? "const " : "")*/
//         + argType + "& "
        /*+ */argument.getName()
        + (lastArgument ? "" : ", ");
    if (argument.getDirection() == "out") {
        _currentOutArgSetter
            << indent(2) << "pAction->setArgument<"
            << argType << ">(\"" << argument.getName()
            << "\", " << argument.getName() 
            << ");" << std::endl;
    }
}


void
DevDeviceCpp::stateVar(const StateVar& stateVar)
{
    if (stateVar.getName().substr(0, std::string("A_ARG_TYPE_").size()) == "A_ARG_TYPE_") {
        return;
    }
    
    std::string stateVarType = _typeMapper[stateVar.getType()];
    _getSet
        // StateVar setter method
        << "void" << std::endl
        << "Dev" + _currentService << "::_set" << stateVar.getName()
        << "(const " << stateVarType << "& val)" << std::endl
        << "{" << std::endl
        << indent(1) << "_pService->setStateVar<" << stateVarType 
        << ">(\"" << stateVar.getName() << "\", val);" << std::endl
        << "}" << std::endl
        << std::endl << std::endl
        << stateVarType << std::endl
        
        // StateVar getter method
        << "Dev" + _currentService << "::_get" << stateVar.getName()
        << "()" << std::endl
        << "{" << std::endl
        << indent(1) << "return _pService->getStateVar<" << stateVarType 
        << ">(\"" << stateVar.getName() << "\");" << std::endl
        << "}" << std::endl
        << std::endl << std::endl;
}


DevDeviceImplH::DevDeviceImplH(DeviceContainer* pDeviceContainer, const std::string& outputPath) :
StubWriter(pDeviceContainer, outputPath),
_out((_outputPath + "Dev" + _deviceName + "Impl.h").c_str())
{
}


void
DevDeviceImplH::deviceContainer(const DeviceContainer& deviceContainer)
{
    _out
        << samplePreamble
        << "#ifndef " << Poco::toUpper(_deviceName) << "_IMPLEMENTATION_H" << std::endl
        << "#define " << Poco::toUpper(_deviceName) << "_IMPLEMENTATION_H" << std::endl
        << std::endl
        << "#include <Omm/Upnp.h>" << std::endl
        << "#include \"" << "Dev" + _deviceName << "Disp.h\"" << std::endl
        << std::endl;
}


void
DevDeviceImplH::deviceContainerEnd(const DeviceContainer& deviceContainer)
{
    _out
        << "#endif" << std::endl
        << std::endl;
}


void
DevDeviceImplH::serviceType(const Service& service)
{
    Omm::Urn serviceType(service.getServiceType());
    std::string serviceName = serviceType.getTypeName();

    _out
        << std::endl
        << "class " << "Dev" + serviceName << "Impl : public " << "Dev" + serviceName << std::endl
        << "{" << std::endl
//         << "public:" << std::endl
//         << serviceName << "Implementation();" << std::endl
//         << std::endl
        << "private:"
        << std::endl;
}


void
DevDeviceImplH::serviceTypeEnd(const Service& service)
{
    _out
        << std::endl
        << indent(1) << "virtual void initStateVars();" << std::endl
//         << std::endl
//         << indent(1) << deviceName << "Implementation* _pDeviceImpl;" << std::endl
//         << std::endl
        << "};" << std::endl
        << std::endl;
}


void
DevDeviceImplH::action(const Action& action)
{
    _out
        << indent(1) << "virtual void " << action.getName() << "("
        ;
}


void
DevDeviceImplH::actionEnd(const Action& action)
{
    _out
        << ");"
        << std::endl;
}


void
DevDeviceImplH::argument(const Argument& argument, bool lastArgument)
{
    _out
        << ((argument.getDirection() == "in") ? "const " : "")
        << _typeMapper[argument.getRelatedStateVarReference()->getType()]
        << "& " << argument.getName()
        << (lastArgument ? "" : ", ")
        ;
}


DevDeviceImplCpp::DevDeviceImplCpp(DeviceContainer* pDeviceContainer, const std::string& outputPath) :
StubWriter(pDeviceContainer, outputPath),
_out((_outputPath + "Dev" + _deviceName + "Impl.cpp.skeleton").c_str())
{
}


void
DevDeviceImplCpp::deviceContainer(const DeviceContainer& deviceContainer)
{
    _out
        << samplePreamble
//         << "#include <Omm/Upnp.h>" << std::endl
        << "#include \"" << "Dev" + _deviceName << "Impl.h\"" << std::endl
        << std::endl;
}


void
DevDeviceImplCpp::serviceType(const Service& service)
{
    _serviceName = Omm::Urn(service.getServiceType()).getTypeName();
    _out
        << "void" << std::endl
        << "Dev" + _serviceName << "Impl::initStateVars()" << std::endl
        << "{" << std::endl
        << "// you may set state variables here with the _set<state_variable_name>() methods" << std::endl
        << "// default values are already set, if defined by the service" << std::endl
        << "}" << std::endl
        << std::endl
        << std::endl;
}


void
DevDeviceImplCpp::action(const Action& action)
{
    _out
        << "void" << std::endl << "Dev" + _serviceName << "Implementation::" << action.getName()
        << "(";
}


void
DevDeviceImplCpp::actionEnd(const Action& action)
{
    _out
        << ")" << std::endl
        << "{" << std::endl
        << "// begin of your own code" << std::endl
        << std::endl
        << "// end of your own code" << std::endl
        << "}" << std::endl
        << std::endl
        << std::endl;
}


void
DevDeviceImplCpp::argument(const Argument& argument, bool lastArgument)
{
    _out
        << ((argument.getDirection() == "in") ? "const " : "")
        << _typeMapper[argument.getRelatedStateVarReference()->getType()]
        << "& " << argument.getName()
        << (lastArgument ? "" : ", ")
        ;
}


DeviceDescH::DeviceDescH(DeviceContainer* pDeviceContainer, const std::string& outputPath) :
StubWriter(pDeviceContainer, outputPath),
_out((_outputPath + _deviceName + "Desc.h").c_str())
{
}


void
DeviceDescH::deviceContainer(const DeviceContainer& deviceContainer)
{
    _out
        << preamble
        << "#ifndef " << Poco::toUpper(_deviceName) << "_DESCRIPTIONS_H" << std::endl
        << "#define " << Poco::toUpper(_deviceName) << "_DESCRIPTIONS_H" << std::endl
        << std::endl
        << "std::string " << "Dev" + _deviceName << "::_deviceDescription =" << std::endl
        << escapeDescription(*deviceContainer.getDeviceDescription())
        << ";" << std::endl
        << std::endl;
}


void
DeviceDescH::deviceContainerEnd(const DeviceContainer& deviceContainer)
{
    _out
        << "#endif" << std::endl
        << std::endl;
}


void
DeviceDescH::serviceType(const Service& service)
{
    Omm::Urn serviceType(service.getServiceType());
    std::string serviceName = serviceType.getTypeName();
    
    _out
        << "std::string " << "Dev" + serviceName << "::_description =" << std::endl
        << escapeDescription(*service.getDescription())
        << ";" << std::endl
        << std::endl;
}


std::string
DeviceDescH::escapeDescription(const std::string& description)
{
    std::string res = description;
    
    // escape all quotes
    std::string::size_type i = 0;
    while ((i = res.find("\"", i)) != std::string::npos) {
        res.insert(i, "\\");
        ++i; ++i;
    }
    
    // delete all carriage returns
    i = 0;
    while ((i = res.find("\r", i)) != std::string::npos) {
        res.erase(i, 1);
    }
    
    // escape all newlines
    i = 0;
    while ((i = res.find("\n", i)) != std::string::npos) {
        res.insert(i, "\\");
        ++i; ++i;
    }
    
    return "\"" + res + "\"";
}


DeviceDescCpp::DeviceDescCpp(DeviceContainer* pDeviceContainer, const std::string& outputPath) :
StubWriter(pDeviceContainer, outputPath),
_out((_outputPath + _deviceName + "Desc.cpp").c_str())
{
}


CtlDeviceImplH::CtlDeviceImplH(DeviceContainer* pDeviceContainer, const std::string& outputPath) :
StubWriter(pDeviceContainer, outputPath),
_out((_outputPath + "Ctl" + _deviceName + "Impl.h").c_str())
{
}


void
CtlDeviceImplH::deviceContainer(const DeviceContainer& deviceContainer)
{
    _out
        << samplePreamble
        << "#ifndef " << Poco::toUpper(_deviceName) << "_CTRL_IMPL_H" << std::endl
        << "#define " << Poco::toUpper(_deviceName) << "_CTRL_IMPL_H" << std::endl
        << std::endl
        << "#include <Omm/Upnp.h>" << std::endl
        << "#include \"" << "Ctl" + _deviceName << ".h\"" << std::endl
        << std::endl;
}


void
CtlDeviceImplH::deviceContainerEnd(const DeviceContainer& deviceContainer)
{
    _out
        << "#endif" << std::endl
        << std::endl;
}


void
CtlDeviceImplH::serviceType(const Service& service)
{
    Omm::Urn serviceType(service.getServiceType());
    std::string serviceName = serviceType.getTypeName();
    
    _out
        << std::endl
        << "class " << "Ctl" + serviceName << "Impl : public " << "Ctl" + serviceName << std::endl
        << "{" << std::endl
        << "private:"
        << std::endl;
}


void
CtlDeviceImplH::serviceTypeEnd(const Service& service)
{
    _out
        << std::endl
        << _eventedStateVars.str()
        << "};" << std::endl
        << std::endl;
    
    _eventedStateVars.str("");
}


void
CtlDeviceImplH::action(const Action& action)
{
    _out
        << indent(1) << "virtual void _ans" << action.getName() << "("
        ;
}


void
CtlDeviceImplH::actionEnd(const Action& action)
{
    _out
        << ");"
        << std::endl;
}


void
CtlDeviceImplH::argument(const Argument& argument, bool lastArgument)
{
    _out
        << "const "
        << _typeMapper[argument.getRelatedStateVarReference()->getType()]
        << "& " << argument.getName()
        << (lastArgument ? "" : ", ")
        ;
}


void
CtlDeviceImplH::stateVar(const StateVar& stateVar)
{
    if (stateVar.getName().substr(0, std::string("A_ARG_TYPE_").size()) == "A_ARG_TYPE_") {
        return;
    }
    
    if (!stateVar.getSendEvents()) {
        return;
    }
    
    _eventedStateVars
        << indent(1) << "virtual void _changed" << stateVar.getName() << "(const "
        << _typeMapper[stateVar.getType()] << "& val);"
        << std::endl;
}


CtlDeviceImplCpp::CtlDeviceImplCpp(DeviceContainer* pDeviceContainer, const std::string& outputPath) :
StubWriter(pDeviceContainer, outputPath),
_out((_outputPath + "Ctl" + _deviceName + "Impl.cpp.skeleton").c_str())
{
}


void
CtlDeviceImplCpp::deviceContainer(const DeviceContainer& deviceContainer)
{
    _out
        << samplePreamble
        << "#include \"" << "Ctl" + _deviceName << "Impl.h\"" << std::endl
        << std::endl;
}


void
CtlDeviceImplCpp::serviceType(const Service& service)
{
    Omm::Urn serviceType(service.getServiceType());
    _serviceName = serviceType.getTypeName();
}


void
CtlDeviceImplCpp::argument(const Argument& argument, bool lastArgument)
{
    _out
        << "const "
        << _typeMapper[argument.getRelatedStateVarReference()->getType()]
        << "& " << argument.getName()
        << (lastArgument ? "" : ", ")
        ;
}


void
CtlDeviceImplCpp::action(const Action& action)
{
    _out
        << "void" << std::endl 
        << "Ctl" + _serviceName << "Impl::_ans" << action.getName()
        << "(";
}


void
CtlDeviceImplCpp::actionEnd(const Action& action)
{
    _out
        << ")" << std::endl
        << "{" << std::endl
        << "// begin of your own code" << std::endl
        << std::endl
        << "// end of your own code" << std::endl
        << "}" << std::endl
        << std::endl
        << std::endl;
}


void
CtlDeviceImplCpp::stateVar(const StateVar& stateVar)
{
    if (stateVar.getName().substr(0, std::string("A_ARG_TYPE_").size()) == "A_ARG_TYPE_") {
        return;
    }
    
    if (!stateVar.getSendEvents()) {
        return;
    }
    
    _out
        << "void" << std::endl 
        << "Ctl" + _serviceName << "Impl::_changed" << stateVar.getName() << "(const "
        << _typeMapper[stateVar.getType()] << "& val)" << std::endl
        << "{" << std::endl
        << "// begin of your own code" << std::endl
        << std::endl
        << "// end of your own code" << std::endl
        << "}" << std::endl
        << std::endl
        << std::endl;
}



CtlDeviceH::CtlDeviceH(DeviceContainer* pDeviceContainer, const std::string& outputPath) :
StubWriter(pDeviceContainer, outputPath),
_out((_outputPath + "Ctl" + _deviceName + ".h").c_str())
{
}


void
CtlDeviceH::deviceContainer(const DeviceContainer& deviceContainer)
{
    _out
        << preamble
        << "#ifndef " << Poco::toUpper(_deviceName) << "_CTRL_H" << std::endl
        << "#define " << Poco::toUpper(_deviceName) << "_CTRL_H" << std::endl
        << std::endl
        << "#include <Omm/Upnp.h>" << std::endl
        << "using Omm::DevDevice;" << std::endl
        << "using Omm::Service;" << std::endl
        << "using Omm::Action;" << std::endl
        << "using Omm::StateVar;" << std::endl
        << "using Omm::StringDescriptionReader;" << std::endl
//        << "using Omm::ui1;" << std::endl
//        << "using Omm::ui2;" << std::endl
//        << "using Omm::ui4;" << std::endl
//        << "using Omm::i1;" << std::endl
//        << "using Omm::i2;" << std::endl
//        << "using Omm::i4;" << std::endl
//        << "using Omm::r4;" << std::endl
//        << "using Omm::r4;" << std::endl
//        << "using Omm::number;" << std::endl
//        << "using Omm::uri;" << std::endl
//        << "using Omm::date;" << std::endl
//        << "using Omm::dateTime;" << std::endl
//        << "using Omm::time;" << std::endl
        << std::endl;
}


void
CtlDeviceH::deviceContainerEnd(const DeviceContainer& deviceContainer)
{
    std::string ctorArgs = "";
    int i = _serviceNames.size();
    while (i--) {
        ctorArgs += "Ctl" + _serviceNames[i] + "* p" + "Ctl" + _serviceNames[i] + (i ? ", " : "");
    }
    
    _out << std::endl
        << "class " << "Ctl" + _deviceName << " : public CtlDevice" << std::endl
        << "{" << std::endl
        << "public:" << std::endl
        << indent(1) << "Ctl" + _deviceName << "("
        << "Device* pDevice, "
        << ctorArgs
        << ");" << std::endl
        << std::endl;
    
    i = _serviceNames.size();
    while (i--) {
        _out << indent(1)
            << "Ctl" + _serviceNames[i] << "* " << _serviceNames[i]
            << "() { return _p" << "Ctl" + _serviceNames[i] << "; }"
            << std::endl;
    }
    
    _out <<  std::endl
        << "private:" << std::endl
        << indent(1) << "virtual void eventHandler(StateVar* pStateVar);" << std::endl
        << std::endl
        ;
    
    i = _serviceNames.size();
    while (i--) {
        _out << indent(1) << "Ctl" + _serviceNames[i] << "* _p" << "Ctl" + _serviceNames[i] << ";" << std::endl;
    }
    
    _out
        << "};" << std::endl
        << std::endl
        << "#endif" << std::endl
        << std::endl;
}


void
CtlDeviceH::serviceType(const Service& service)
{
    Omm::Urn serviceType(service.getServiceType());
    std::string serviceName = serviceType.getTypeName();
    _serviceNames.push_back(serviceName);
    
    _out
        << "class " << "Ctl" + serviceName << std::endl
        << "{" << std::endl
        << indent(1) << "friend class " << "Ctl" + _deviceName << std::endl
        << std::endl
        << "public:"
        << std::endl;
}


void
CtlDeviceH::serviceTypeEnd(const Service& service)
{
    _out
        << std::endl
        << _reqAction.str()
        << std::endl
        << _getEventedStateVars.str()
        << std::endl
        << "protected:" << std::endl
        << _ansAction.str()
        << std::endl
        << _changeEventedStateVars.str()
        << std::endl
        << "private:" << std::endl
        << _threadAction.str()
        << std::endl
        << indent(1) << "Service* _pService;" << std::endl
        << "};" << std::endl
        << std::endl;
    
    _reqAction.str("");
    _ansAction.str("");
    _threadAction.str("");
    _getEventedStateVars.str("");
    _changeEventedStateVars.str("");
}


void
CtlDeviceH::action(const Action& action)
{
    _out
        << indent(1) << "void " << action.getName() << "("
        ;
    _reqAction
        << indent(1) << "void _req" << action.getName() << "("
        ;
    _ansAction
        << indent(1) << "virtual void _ans" << action.getName() << "("
        ;
    _threadAction
        << indent(1) << "void _thread" << action.getName() << "("
        ;
}


void
CtlDeviceH::actionEnd(const Action& action)
{
    _out
        << ");"
        << std::endl;
    
    std::string reqActionArgs = _reqActionArgs.str();
    std::string::size_type l = reqActionArgs.length();
    if (l >= 2 && reqActionArgs.substr(l - 2) == ", ") {
        reqActionArgs = reqActionArgs.substr(0, l - 2);
    }
    _reqAction
        << reqActionArgs
        << ");"
        << std::endl;
    _ansAction
        << _ansActionArgs.str()
        << ") = 0;"
        << std::endl;
    _threadAction
        << "Action* pAction);"
        << std::endl;
    
    _reqActionArgs.str("");
    _ansActionArgs.str("");
}


void
CtlDeviceH::argument(const Argument& argument, bool lastArgument)
{
    _out
        << ((argument.getDirection() == "in") ? "const " : "")
        << _typeMapper[argument.getRelatedStateVarReference()->getType()]
        << "& " << argument.getName()
        << (lastArgument ? "" : ", ")
        ;
    
    if (argument.getDirection() == "in") {
        _reqActionArgs
            << "const "
            << _typeMapper[argument.getRelatedStateVarReference()->getType()]
            << "& " << argument.getName()
            << (lastArgument ? "" : ", ")
            ;
    }
    
    _ansActionArgs
        << "const "
        << _typeMapper[argument.getRelatedStateVarReference()->getType()]
        << "& " << argument.getName()
        << (lastArgument ? "" : ", ")
        ;
}


void
CtlDeviceH::stateVar(const StateVar& stateVar)
{
    if (stateVar.getName().substr(0, std::string("A_ARG_TYPE_").size()) == "A_ARG_TYPE_") {
        return;
    }
    
    if (!stateVar.getSendEvents()) {
        return;
    }
    
    _getEventedStateVars
        << indent(1)
        << _typeMapper[stateVar.getType()] << " "
        << "_get" << stateVar.getName() << "();"
        << std::endl;
    
    _changeEventedStateVars
        << indent(1) << "virtual void _changed" << stateVar.getName() << "(const "
        << _typeMapper[stateVar.getType()] << "& val) = 0;"
        << std::endl;
}


CtlDeviceCpp::CtlDeviceCpp(DeviceContainer* pDeviceContainer, const std::string& outputPath) :
StubWriter(pDeviceContainer, outputPath),
_out((_outputPath + "Ctl" + _deviceName + ".cpp").c_str())
{
}


void
CtlDeviceCpp::deviceContainer(const DeviceContainer& deviceContainer)
{
    _out
        << preamble
        << "#include \"" << "Ctl" + _deviceName << ".h\"" << std::endl
        << std::endl;
    
    _firstStateVar = true;
}


void
CtlDeviceCpp::deviceContainerEnd(const DeviceContainer& deviceContainer)
{
    std::string ctorArgs = "";
//     std::string implPointers = "";
    int i = _serviceNames.size();
    while (i--) {
        ctorArgs += "Ctl" + _serviceNames[i] + "* p" + "Ctl" + _serviceNames[i] + (i ? ", " : "");
    }
    
    // Event dispatcher
    
    _out
        << "void" << std::endl
        << "Ctl" + _deviceName << "::eventHandler(StateVar* pStateVar)" << std::endl
        << "{" << std::endl
        << _eventDispatcher.str()
        << "}" << std::endl
        << std::endl;
    
    // Device ctor ...
    _out << std::endl
//         << "class " << _deviceName << "Controller : public CtlDevice" << std::endl
//         << "{" << std::endl
//         << "public:" << std::endl
        << "Ctl" + _deviceName << "::" << "Ctl" + _deviceName << "("
        << "Device* pDevice, "
        << ctorArgs
        << ") :" << std::endl
        << "CtlDevice(pDevice)," << std::endl
            ;
    
    i = _serviceNames.size();
    while (i--) {
        _out
            << "_p" << "Ctl" + _serviceNames[i] << "(p"
            << "Ctl" + _serviceNames[i] << ")" <<  (i ? ", " : "") << std::endl;
    }
    
    _out
        << "{" << std::endl;
    
    i = _serviceNames.size();
    while (i--) {
        _out
                    
            << indent(1) << "_p" << "Ctl" + _serviceNames[i] << "->_pService = "
            << "_pDevice->getService(\"" << _serviceTypes[i] << "\");"
            << std::endl;
    }
    
    _out
        << std::endl
        << indent(1) << "init();" << std::endl
        << "}" << std::endl
        << std::endl;
    
//     i = _serviceNames.size();
//     while (i--) {
//         _out << indent(1)
//             << _serviceNames[i] << "Controller* " << _serviceNames[i] 
//             << "() { return _p" << _serviceNames[i] << "Controller; }"
//             << std::endl;
//     }
//     
//     _out <<  std::endl
//         << "private:" << std::endl
//         << indent(1) << "virtual void eventHandler(StateVar* pStateVar);" << std::endl
//         << std::endl
//         << indent(1) << "Device* _pDevice;" << std::endl
//         ;
//     
//     i = _serviceNames.size();
//     while (i--) {
//         _out << indent(1) << _serviceNames[i] << "Controller* _p" << _serviceNames[i] << "Controller;" << std::endl;
//     }
//     
//     _out
//         << "};" << std::endl
//         << std::endl
//         << "#endif" << std::endl
//         << std::endl;
}


void
CtlDeviceCpp::serviceType(const Service& service)
{
    Omm::Urn serviceType(service.getServiceType());
    _serviceTypes.push_back(service.getServiceType());
    std::string serviceName = serviceType.getTypeName();
    _serviceNames.push_back(serviceName);
    _currentService = serviceName;
}


void
CtlDeviceCpp::serviceTypeEnd(const Service& service)
{
    _out
        << std::endl
        << _reqAction.str()
//         << std::endl
/*        << _getEventedStateVars.str()
        << std::endl
        << "protected:" << std::endl
        << _ansAction.str()
        << std::endl
        << _changeEventedStateVars.str()
        << std::endl
        << "private:" << std::endl*/
        << _threadAction.str()
        << std::endl
//         << indent(1) << "Service* _pService;" << std::endl
//         << "};" << std::endl
        << std::endl;
    
    _reqAction.str("");
//     _ansAction.str("");
    _threadAction.str("");
//     _getEventedStateVars.str("");
//     _changeEventedStateVars.str("");
}


void
CtlDeviceCpp::action(const Action& action)
{
    _out
        << "void" << std::endl
        << "Ctl" + _currentService << "::" << action.getName() << "("
        ;
    _reqAction
        << "void " << std::endl
        << "Ctl" + _currentService << "::_req" << action.getName() << "("
        ;
    _threadAction
        << "void " << std::endl
        << "Ctl" + _currentService << "::_thread" << action.getName() << "("
        << "Action* pAction"
        ;
}


void
CtlDeviceCpp::actionEnd(const Action& action)
{
    _out
        << ")" << std::endl
        << "{" << std::endl
        << indent(1) << "Action* pAction = _pService->getAction(\"" 
        << action.getName() << "\")->clone();" << std::endl
        << _inArgSetter.str()
        << indent(1) << "_pService->sendAction(pAction);" << std::endl
        << _outArgGetter.str()
        << "}" << std::endl
        << std::endl;
    
    std::string reqActionArgs = _reqActionArgs.str();
    std::string::size_type l = reqActionArgs.length();
    if (l >= 2 && reqActionArgs.substr(l - 2) == ", ") {
        reqActionArgs = reqActionArgs.substr(0, l - 2);
    }
    _reqAction
        << reqActionArgs
        << ")" << std::endl
        << "{" << std::endl
        << indent(1) << "Action* pAction = _pService->getAction(\"" 
        << action.getName() << "\")->clone();" << std::endl
        << _inArgSetter.str()
        << indent(1) << "ActionThread<"
        << "Ctl" + _currentService << "> thread(this, &"
        << "Ctl" + _currentService << "::_thread" << action.getName() << ", pAction);" << std::endl
        << indent(1) << "thread.start();" << std::endl
        << "}" << std::endl
        << std::endl;

    _threadAction
        << ")" << std::endl
        << "{" << std::endl
        << indent(1) << "_pService->sendAction(pAction);" << std::endl
        << _inArgGetter.str()
        << _outArgGetterLocal.str()
        << indent(1) << "_ans" << action.getName() << "(" << _allArgsCall.str() << ");" << std::endl
        << "}" << std::endl
        << std::endl;
    
    _inArgSetter.str("");
    _inArgGetter.str("");
    _outArgGetter.str("");
    _outArgGetterLocal.str("");
    _reqActionArgs.str("");
    _allArgsCall.str("");
}


void
CtlDeviceCpp::argument(const Argument& argument, bool lastArgument)
{
    std::string argType = _typeMapper[argument.getRelatedStateVarReference()->getType()];
    
    _out
        << ((argument.getDirection() == "in") ? "const " : "")
        << argType
        << "& " << argument.getName()
        << (lastArgument ? "" : ", ")
        ;
    
    _allArgsCall
        << argument.getName()
        << (lastArgument ? "" : ", ")
        ;
    
    if (argument.getDirection() == "in") {
        _inArgSetter
            << indent(1) << "pAction->setArgument<" << argType << ">(\""
            << argument.getName() << "\", "
            << argument.getName() << ");"
            << std::endl;
        
        _inArgGetter
            << indent(1) << argType << " " << argument.getName()
            << " = pAction->getArgument<" << argType << ">(\""
            << argument.getName() << "\");"
            << std::endl;
        
        _reqActionArgs
            << "const "
            << argType
            << "& " << argument.getName()
            << (lastArgument ? "" : ", ")
            ;
    }
    else if (argument.getDirection() == "out") {
        _outArgGetter
            << indent(1) << argument.getName()
            << " = pAction->getArgument<" << argType << ">(\""
            << argument.getName() << "\");"
            << std::endl;
        
        _outArgGetterLocal
            << indent(1) << argType << " " << argument.getName()
            << " = pAction->getArgument<" << argType << ">(\""
            << argument.getName() << "\");"
            << std::endl;
    }
    
//     if (argument.getDirection() == "in") {
//     }
    
//     _ansActionArgs
//         << "const "
//         << argType
//         << "& " << argument.getName()
//         << (lastArgument ? "" : ", ")
//         ;
}


void
CtlDeviceCpp::stateVar(const StateVar& stateVar)
{
    std::string varType = _typeMapper[stateVar.getType()];
    
    if (stateVar.getName().substr(0, std::string("A_ARG_TYPE_").size()) == "A_ARG_TYPE_") {
        return;
    }
    
    if (!stateVar.getSendEvents()) {
        return;
    }
    
//     _getEventedStateVars
//         << indent(1)
//         << varType << " "
//         << "_get" << stateVar.getName() << "();"
//         << std::endl;
//     
//     _changeEventedStateVars
//         << indent(1) << "virtual void _changed" << stateVar.getName() << "(const "
//         << varType << "& val) = 0;"
//         << std::endl;
    
    _eventDispatcher
        << indent(1) << (_firstStateVar ? "" : "else ")
        << "if (pStateVar->getName() == \"" << stateVar.getName() << "\") {" << std::endl
        << indent(2) << varType << " val;" << std::endl
        << indent(2) << "pStateVar->getValue(val);" << std::endl
        << indent(2) << "_p" << "Ctl" + _currentService << "->_changed" << stateVar.getName() << "(val);" << std::endl
        << indent(1) << "}" << std::endl;
    
    _out
        << varType << std::endl
        << "Ctl" + _currentService << "::_get" << stateVar.getName() << "()" << std::endl
        << "{" << std::endl
        << indent(1) << "return _pService->getStateVar<" << varType << ">(\"" << stateVar.getName() << "\");" << std::endl
        << "}" << std::endl
        << std::endl;
    
    _firstStateVar = false;
}